### ISSUE TITLE
Unable to run Arch Linux

### ISSUE THREAD

**Issue by DaBrookePlayz** [DebianArch64/DebProvision#10]
I downloaded the binary (AMD64) for my computer (x86_64, also known as AMD64), and used chmod +x (file) for it. I executed it, and it stops or crashes immediately with no response at all.

**Comment by DebianArch64** [comment]
Hey, thanks for letting me know this issue was going on. I recompiled the Linux builds and they all seem to be working fine - tell me if this solves your issue :D

![PXL_20220530_123513803](https://user-images.githubusercontent.com/63203414/170993598-35ecd949-bbaa-49cc-9ed8-cd9213a4685c.jpg)

**Comment by Cinytax** [comment]
I have same issue now. I downloaded same binary file(x86_64, also known as AMD64). I execute the file but nothing happens.
