### ISSUE TITLE
can't install scarlet

### ISSUE THREAD

**Issue by clovdystackflow** [DebianArch64/DebProvision#102]
i've tried to download scarletcloud multiple times now, it only worked twice but it got revoked because i forgot to refresh it and now whenever i try and install it i keep getting error -22421, i did setup native anissette so i dont really know what the problem here is

**Comment by DebianArch64** [comment]
> i've tried to download scarletcloud multiple times now, it only worked twice but it got revoked because i forgot to refresh it and now whenever i try and install it i keep getting error -22421, i did setup native anissette so i dont really know what the problem here is

Apple invalidated your computer ADI - delete all files in this folder and it'll fix it for you

C:\ProgramData\Apple Computer\iTunes\adi
