### ISSUE TITLE
Anisette fetch timed out. Make sure AnisettePlugin is enabled and Mail app is open.

### ISSUE THREAD

**Issue by albasyir** [DebianArch64/DebProvision#105]
scarlet needs a plugin that should be installed on mail, however, i have problem, 

```
Anisette fetch timed out. Make sure AnisettePlugin is enabled and the Mail app is open.
anisette is empty (server error)
```

i have tried to manage the plugin but, there's no plugin menu anymore
<img width="790" alt="image" src="https://user-images.githubusercontent.com/28939309/215309612-ca1bebd9-a260-45e9-9652-0471d3b7ab1a.png">

this mail version that i use for : 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/28939309/215309547-ba2da8f1-8e62-4f0c-b24d-74a7ede34f1b.png">

**Comment by DebianArch64** [comment]
> scarlet needs a plugin that should be installed on mail, however, i have problem,
> 
> ```
> Anisette fetch timed out. Make sure AnisettePlugin is enabled and the Mail app is open.
> anisette is empty (server error)
> ```
> 
> i have tried to manage the plugin but, there's no plugin menu anymore <img alt="image" width="790" src="https://user-images.githubusercontent.com/28939309/215309612-ca1bebd9-a260-45e9-9652-0471d3b7ab1a.png">
> 
> this mail version that i use for : <img alt="image" width="251" src="https://user-images.githubusercontent.com/28939309/215309547-ba2da8f1-8e62-4f0c-b24d-74a7ede34f1b.png">

If you updated your computer make sure to re-run the MailPlugin install step as shown in the video:
https://youtu.be/yeA78WKxEXg

If you still have the issue run this in terminal - ScarletCloud should automatically be running this:
sudo defaults write /Library/Preferences/com.apple.mail EnableBundles -bool YES
