### ISSUE TITLE
Unable to sideload

### ISSUE THREAD

**Issue by DaBrookePlayz** [DebianArch64/DebProvision#11]
Running through Arch Linux, connected to stock ios device.
![Screenshot_2022-06-01_19-04-39](https://user-images.githubusercontent.com/73117146/171521953-71a76598-593d-42e2-b43e-1c0a2970f070.png)
![Screenshot_2022-06-01_19-13-58](https://user-images.githubusercontent.com/73117146/171521954-af7d0e44-f60c-40e4-9141-bbecc3dd5242.png)

**Comment by DebianArch64** [comment]
That's an issue of signing the app when it's contacting my API - shouldn't happen constantly give it a try after a few minutes have passed. Every other part of the process has worked so far, so just this last part needs to work 🤪

**Comment by DaBrookePlayz** [comment]
Waiting isn't working... is there a temporary way to fix it?
![Screenshot_2022-06-01_19-58-55](https://user-images.githubusercontent.com/73117146/171525453-349cc36e-f1b2-42f0-b528-835115b28ac4.png)
