### ISSUE TITLE
about anisette

### ISSUE THREAD

**Issue by AdverseMiller** [DebianArch64/DebProvision#111]
I know you can change anisette server in the scarlet app itself if needed, but is there a way to change the anisette server for when *just* installing scarlet?

**Comment by DebianArch64** [comment]
> I know you can change anisette server in the scarlet app itself if needed, but is there a way to change the anisette server for when _just_ installing scarlet?

At the moment no. Maybe something that'll be added in the future, but at the moment focus is on mitigating ongoing attacks from my competitors and the new install method

**Comment by DebianArch64** [comment]
Scarlet no longer needs the user to put in an anisette server and supports native anisette with windows and mac
