### ISSUE TITLE
They lock my account just after starting installation

### ISSUE THREAD

**Issue by VladChekunov** [DebianArch64/DebProvision#112]
This Apple ID has been locked for security reasons. Visit iForgot to reset your account (https://iforgot.apple.com). (-20209)

**Comment by DebianArch64** [comment]
> This Apple ID has been locked for security reasons. Visit iForgot to reset your account (https://iforgot.apple.com). (-20209)

This has nothing to do with ScarletCloud. Don't use wireguard or Linux computer to avoid these issues. Apple doesn't like server anisette your computer must be the one to generate it.

ScarletCloud must be opened for installs and it tells you if any issues have occurred

![Screenshot_20230210-122600](https://user-images.githubusercontent.com/63203414/218168734-cb76e98e-939b-4b74-869f-17c56713b024.png)
