### ISSUE TITLE
> this error shows up while trying to install any app from any sideloading service (sideloadly, altstore and obv scarlet)

### ISSUE THREAD

**Issue by zin55** [DebianArch64/DebProvision#114]
> this error shows up while trying to install any app from any sideloading service (sideloadly, altstore and obv scarlet)

I've seen this happen only with one other person it was very weird, but I believe I know the root cause

Apple knows an app is installed by it's mobileprovision it extracts from the app then stores it on the system.
When an app is uninstalled it's supposed to remove this mobileprovision, but if apple fails to do this that app is listed as installed forever

Is this the issue you are experiencing? A three app limit error with apps you already uninstalled ? If so contact me on Twitter @GetScarlet

_Originally posted by @DebianArch64 in https://github.com/DebianArch64/DebProvision/issues/88#issuecomment-1366282794_

**Comment by DebianArch64** [comment]
Duplicates not allowed
