### ISSUE TITLE
Scarlet Not Installing

### ISSUE THREAD

**Issue by Profility** [DebianArch64/DebProvision#118]
When selecting the "(re)install Scarlet" option and after putting in the code, this error pops up:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x83d1ccf]

goroutine 6 [running]:
usescarlet.com/debserver/gsa.(*ProvisionAPI).ManageCert.func1()
        /Users/debianarch/Documents/ScarletGSA/debprovision.go:102 +0x3f
usescarlet.com/debserver/gsa.(*ProvisionAPI).ManageCert(0xa3d2340)
        /Users/debianarch/Documents/ScarletGSA/debprovision.go:131 +0x329
main.installScarlet(0xa3d2340, {0x851ca64, 0xa196300})
        /Users/debianarch/Documents/ScarletServer/main.go:469 +0x1be
main.deviceListenerCLI.func1()
        /Users/debianarch/Documents/ScarletServer/main.go:564 +0x368
created by main.deviceListenerCLI
        /Users/debianarch/Documents/ScarletServer/main.go:541 +0x162
```

I am using Ubuntu Server 22.04.

**Comment by DebianArch64** [comment]
> When selecting the "(re)install Scarlet" option and after putting in the code, this error pops up:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x83d1ccf]
> 
> goroutine 6 [running]:
> usescarlet.com/debserver/gsa.(*ProvisionAPI).ManageCert.func1()
>         /Users/debianarch/Documents/ScarletGSA/debprovision.go:102 +0x3f
> usescarlet.com/debserver/gsa.(*ProvisionAPI).ManageCert(0xa3d2340)
>         /Users/debianarch/Documents/ScarletGSA/debprovision.go:131 +0x329
> main.installScarlet(0xa3d2340, {0x851ca64, 0xa196300})
>         /Users/debianarch/Documents/ScarletServer/main.go:469 +0x1be
> main.deviceListenerCLI.func1()
>         /Users/debianarch/Documents/ScarletServer/main.go:564 +0x368
> created by main.deviceListenerCLI
>         /Users/debianarch/Documents/ScarletServer/main.go:541 +0x162
> ```
> 
> I am using Ubuntu Server 22.04.

This wouldn't be a good fit anyways since your server must have been connected physically to your phone before in order for wireless modes to be possible

If your goal is for computerless part of Scarlet it's recommended to use either the direct method or paid developer account login with the standard version of Scarlet

If you have a normal account and want computerless setup wireguard - DM me on twitter and we can go over this further @GetScarlet

**Comment by DebianArch64** [comment]
Issue was caused by your account somehow not being affiliated with any teams - try logging into apple's developer website

Next update will push the fix for the crash
