### ISSUE TITLE
Scarlet loop crash

### ISSUE THREAD

**Issue by KanekiLeChomeur** [DebianArch64/DebProvision#119]
After I reinstalled Scarlet, some crash loop showed up when I'm connected to the Scarlet Server while It tries to Send anisette support type

**Comment by fuqityoo** [comment]
have the same issue, any solution yet?

**Comment by g3yt** [comment]
Same here, hopefully someone has a solution soon.

**Comment by DebianArch64** [comment]
I pushed a quick fix tell me if it helps - I can't seem to reproduce it on my Mac, but this should work

**Comment by DebianArch64** [comment]
Officially fixed. Also make sure to update the Scarlet app by clicking "Install Scarlet" from ScarletCloud that fixes another crash

**Comment by DebianArch64** [comment]
My bad now it's fixed. You just need to update the Scarlet app by clicking "Install Scarlet" from ScarletCloud - I also cracked down other issues at the same time

**Comment by zin55** [comment]
> After I reinstalled Scarlet, some crash loop showed up when I'm connected to the Scarlet Server while It tries to Send anisette support type
