### ISSUE TITLE
Failed Installing Scarlet: failed with status: 403 (https://resources.usescarlet.com/api/sign?beta=30)

### ISSUE THREAD

**Issue by BeholdTheKing** [DebianArch64/DebProvision#125]
- Please wait as Scarlet sideloads.
failed with status: 403 (https://resources.usescarlet.com/api/sign?beta=30)

**Comment by DebianArch64** [comment]
> * Please wait as Scarlet sideloads.
>   failed with status: 403 (https://resources.usescarlet.com/api/sign?beta=30)

I see that in logs three people are being flagged as "Bot" security - wouldn't be surprised if that was the 403 message

ScarletCloud is switching to serverless signing this week will close this post when the transition is done - so far from my testing works fine for MacOS now I need to port windows

In the meantime today I'll make cloudflare force allow all connections to that part of my API and hope I don't get billed much from it

**Comment by BeholdTheKing** [comment]
Thanks for that.  I just tried again however and received the same error.

**Comment by DebianArch64** [comment]
> Thanks for that. I just tried again however and received the same error.

I forgot to push the changes to cloudflare - try now and I'm 100% certain it'll work now  😜

**Comment by BeholdTheKing** [comment]
Unfortunately I'm getting the same error.  Is the attempt even showing up on your end? Maybe it's something I'm doing?

**Comment by Hann8n** [comment]
I am also having this issue

**Comment by klyoml** [comment]
I have a little different from yours
- Please wait as Scarlet sideloads.
Post "https://resources.usescarlet.com/api/sign?beta=30": net/http: timeout awaiting response headers

**Comment by heyimdumblol** [comment]
> I have a little different from yours
> 
> * Please wait as Scarlet sideloads.
>   Post "https://resources.usescarlet.com/api/sign?beta=30": net/http: timeout awaiting response headers

i have the same issue

**Comment by CMihai99** [comment]
> I have a little different from yours
> 
> * Please wait as Scarlet sideloads.
>   Post "https://resources.usescarlet.com/api/sign?beta=30": net/http: timeout awaiting response headers

same here, i got the same issue with no success

**Comment by DebianArch64** [comment]
Closing this because the new ScarletCloud build does signing natively and will soon have a direct sideload option to make the Scarlet app optional

**Comment by BeholdTheKing** [comment]
Sorry but I tried it again and I still get the same error. Is the native signing supposed to fix this?

**Comment by Flanderzz** [comment]
im still getting this error

**Comment by epicgamer40** [comment]
How to fix?

**Comment by przzzzzxx** [comment]
he closed this but people are still having the problem and there is no way around it, great
