### ISSUE TITLE
password protected

### ISSUE THREAD

**Issue by Coolmar145** [DebianArch64/DebProvision#126]
everytime i try to sign in it says password protect, mb if im being dumb
![image](https://user-images.githubusercontent.com/50529934/226050847-c481012b-8074-4371-aaab-7d17c43f2b9f.png)

**Comment by Kostadinosk** [comment]
you must unlock your phone first then retry

**Comment by DebianArch64** [comment]
> you must unlock your phone first then retry

Yeah pretty sure this is it - either that or means there is no password on the phone, but my phone doesn't have a password and it's fine
