### ISSUE TITLE
How to add personal anisette server link on Scarlet-cloud-linux?

### ISSUE THREAD

**Issue by dokemodo** [DebianArch64/DebProvision#129]
Im using debian arch64 on raspberry pi. i already setup myself anisette server by docker and i am using that to run altserver on linux.
Today im trying to using Scarlet-cloud on my raspberry pi, but i can't setting personal anisette server, so that apple blocked my id again, and ofcouse, i can't use Scalet-cloud-linux.

Can you add any function to add personal anisette server on Scalet-cloud-linux. It wold be perfect because linux server can run 24/24

**Comment by erenerturk1** [comment]
+1 hoping to do the same with docker compose using [Provision](https://github.com/Dadoum/Provision#docker-container)

**Comment by DebianArch64** [comment]
Hello computer method got a major update now it has a no account locking anisette server built-in
