### ISSUE TITLE
Can't download an app 

### ISSUE THREAD

**Issue by SquiddGame** [DebianArch64/DebProvision#13]
It stucks everytime at 49% and says this : 
I've tried on another iPhone and it works perfect but for some reason not on this one, I've tried to uninstall and reinstall but it doesn't change anything.
![IMG_C4D8AE1126D0-1](https://user-images.githubusercontent.com/106984250/172435524-010cfbfd-da4b-481e-b72f-1daca3194204.jpeg)

**Comment by KevinAlavik** [comment]
Try to resinstall scarlet

**Comment by KevinAlavik** [comment]
Try to resinstall scarlet

**Comment by KevinAlavik** [comment]
Try to resinstall scarlet

**Comment by letankhai442** [comment]
leave coment

**Comment by Zany-Zachary1** [comment]
This happened a few times for me too, but a few reinstalls andreboots fixed it.
