### ISSUE TITLE
it does not work there is an error

### ISSUE THREAD

**Issue by Doctor2023** [DebianArch64/DebProvision#134]
![IMG_0569](https://user-images.githubusercontent.com/129991276/230984738-fb8b04b1-2cf4-4497-a665-91bd4a1ef3f1.jpeg)

i cant install scarletcloud

**Comment by SpektacleFR** [comment]
Any error code or logs?  Is the MailPlugin enabled?

**Comment by DebianArch64** [comment]
> ![IMG_0569](https://user-images.githubusercontent.com/129991276/230984738-fb8b04b1-2cf4-4497-a665-91bd4a1ef3f1.jpeg)
> 
> i cant install scarletcloud

MailPlugin must be enabled for login to work - follow this video guide:
https://youtu.be/yeA78WKxEXg
