### ISSUE TITLE
403 Error "failed with status: 403 (https://resources.usescarlet.com/api/sign?beta=30)"

### ISSUE THREAD

**Issue by ahdeddd** [DebianArch64/DebProvision#135]
I am trying to sideload to my Iphone 13 (ios 15.7) from my laptop running Arch Linux.

This is what my terminal says after running the command `./scarletcloud-linux-386`

```
WARNING: Native anisette not setup by you. Login issues may occur.
Failed starting wireless boostrapper: listen tcp :6969: bind: address already in use
Waiting for device to be connected...
Connected -> 00008110-00023D303AE1801E
✔ (re)install Scarlet
Enter Email: [email]
Enter Password: [password]
- Please wait as Scarlet sideloads.
[Generating certificate] ->
failed with status: 403 (https://resources.usescarlet.com/api/sign?beta=30)
```

Can someone tell me how I can fix this issue? Do I need a native anisette server? If so, how can I get that to work?

Thanks.

**Comment by ahdeddd** [comment]
I just fixed the `Failed starting wireless boostrapper: listen tcp :6969: bind: address already in use` as I had something else running on :6969.

But that hasn't resolved the issue.

**Comment by DebianArch64** [comment]
Closing this because the new ScarletCloud build does signing natively and will soon have a direct sideload option to make the Scarlet app optional
