### ISSUE TITLE
Mail plug-in not supported 

### ISSUE THREAD

**Issue by magnumoh** [DebianArch64/DebProvision#137]
Mail plug-in is not supported, any advice?
![Screen Shot 2023-04-24 at 11 53 01](https://user-images.githubusercontent.com/131641286/233906924-aa72fccc-2a0a-4e03-9904-e0bcc3d74b31.png)

**Comment by DebianArch64** [comment]
> Mail plug-in is not supported, any advice?
> ![Screen Shot 2023-04-24 at 11 53 01](https://user-images.githubusercontent.com/131641286/233906924-aa72fccc-2a0a-4e03-9904-e0bcc3d74b31.png)

This is apart of apple's Mail app restriction - I recommend doing this on windows instead because it doesn't need all that setup

In the future I can add support for using XPC directly for anisette generation on Mac's that have SIP disabled

**Comment by magnumoh** [comment]
Thanks for the info given
