### ISSUE TITLE
[Bug/Anisette] Anisette causing ScarletCloud/DebProvision to not sign Scarlet/IPAs on Scarlet

### ISSUE THREAD

**Issue by LunarN0v4** [DebianArch64/DebProvision#139]
Running as root (> sudo ./scarletcloudux-linux-amd64 <)

WARNING: Native anisette not setup by you. Login issues may occur.
Listening on :6969
Connected -> <REDACTEDBYN0V4>
<REDACTEDBYN0V4>
Unable to sign you in to your Apple ID. Try again later. (-36607)

**Comment by DebianArch64** [comment]
> Running as root (> sudo ./scarletcloudux-linux-amd64 <)
> 
> WARNING: Native anisette not setup by you. Login issues may occur. Listening on :6969 Connected -> Unable to sign you in to your Apple ID. Try again later. (-36607)

Yep this is apart of the warning. To sum it up Apple has special headers called anisette that represents a real *Mac*. 

For the past few years the only way to generate anisette is with a mailplugin for mac (to get the right entitlements). For windows it's generated with itunes DLL libraries

Recently it was found that on Linux apple music libraries could be used. I have to check out the legality of implementing that in ScarletCloud for Linux, but at the moment anisette servers are used which apple easily distrusts on certain devices

**Comment by WillXProject** [comment]
> > Running as root (> sudo ./scarletcloudux-linux-amd64 <)
> 
> > 
> 
> > WARNING: Native anisette not setup by you. Login issues may occur. Listening on :6969 Connected -> Unable to sign you in to your Apple ID. Try again later. (-36607)
> 
> 
> 
> Yep this is apart of the warning. To sum it up Apple has special headers called anisette that represents a real *Mac*. 
> 
> 
> 
> For the past few years the only way to generate anisette is with a mailplugin for mac (to get the right entitlements). For windows it's generated with itunes DLL libraries
> 
> 
> 
> Recently it was found that on Linux, android apple music libraries could be used. I have to check out the legality of implementing that in ScarletCloud for Linux, but at the moment anisette servers are used which apple easily distrusts on certain devices

If you need help with it, I'm here, I'm a fellow programmer and could definitely help out

**Comment by DebianArch64** [comment]
> > > Running as root (> sudo ./scarletcloudux-linux-amd64 <)
> > 
> > 
> > > 
> > 
> > 
> > > WARNING: Native anisette not setup by you. Login issues may occur. Listening on :6969 Connected -> Unable to sign you in to your Apple ID. Try again later. (-36607)
> > 
> > 
> > Yep this is apart of the warning. To sum it up Apple has special headers called anisette that represents a real _Mac_.
> > For the past few years the only way to generate anisette is with a mailplugin for mac (to get the right entitlements). For windows it's generated with itunes DLL libraries
> > Recently it was found that on Linux, android apple music libraries could be used. I have to check out the legality of implementing that in ScarletCloud for Linux, but at the moment anisette servers are used which apple easily distrusts on certain devices
> 
> If you need help with it, I'm here, I'm a fellow programmer and could definitely help out

Give me a message on Discord I need to release some of this stuff during the summer and need testers/feedback - DebianArch#1935

**Comment by DebianArch64** [comment]
I accidentally closed it xD

**Comment by WillXProject** [comment]
lol

**Comment by WillXProject** [comment]
> I accidentally closed it xD

hey Debian, still haven't gotten a friend request accepted notif, my Discord is N0v4#4471

**Comment by WillXProject** [comment]
Debian? I'm still waiting for action on this, if you've fixed it, please tell me.

**Comment by P00FY** [comment]
> 

i need help it says 

FAILED
Setup native anisette on the computer

**Comment by P00FY** [comment]
> 

please help me

**Comment by DebianArch64** [comment]
> > 
> 
> i need help it says
> 
> FAILED Setup native anisette on the computer

This is unrelated to the thread you messaged in - if on windows make sure icloud and itunes are installed. If on Mac make sure the Mailplugin is enabled

**Comment by LunarN0v4** [comment]
I've taken a look and I'm pretty confused on how you'd end up with an anisette for Linux, rn what I'm seeing is you could just plug in your phone every week to your pc and run a Windows KVM with QEMU, it works for me.

**Comment by mrblack1011** [comment]
> > 
> 
> i need help it says
> 
> FAILED Setup native anisette on the computer

Did you fix it??, i got the same problem

**Comment by DebianArch64** [comment]
> > > 
> > 
> > 
> > i need help it says
> > FAILED Setup native anisette on the computer
> 
> Did you fix it??, i got the same problem

Nothing to fix, anisette is required for login to work for free developer accounts. On windows iCloud and iTunes are required from non-microsoft store and on Mac versions below Sonoma require a mailplugin

If you don't want to use a computer for installs enable wireguard. Also make sure you are using the new ScarletCloud builds if using Linux

**Comment by reeky92** [comment]
yo so I sideload scarlet into my iPad but as I add a file in it says I need to setup native anisette. I search it up and all I can find is how to set up anisette for sideload, So I tried doing what they told me to do, go on mail, preference and manage plug in. I don't know if it my laptop new update and that vid is outdated or that it just dosent detect it but the thing isn't even there. I search on apple and I need to go extension but there's nothing there. I was planning on contacting @getscarlet twitter but it says I have to verify by purchasing a subsciption

**Comment by LunarN0v4** [comment]
> yo so I sideload scarlet into my iPad but as I add a file in it says I need to setup native anisette. I search it up and all I can find is how to set up anisette for sideload, So I tried doing what they told me to do, go on mail, preference and manage plug in. I don't know if it my laptop new update and that vid is outdated or that it just dosent detect it but the thing isn't even there. I search on apple and I need to go extension but there's nothing there. I was planning on contacting @getscarlet twitter but it says I have to verify by purchasing a subsciption
> 
> 

This is an old issue, please open a new one instead of replying to an old one that's already closed.
