### ISSUE TITLE
Sideloaded Scarlet crushes

### ISSUE THREAD

**Issue by ArtGMlg** [DebianArch64/DebProvision#140]
When I'm installing Scarlet by ScarletCloud-windows-386, it successfully sideloads, but I can't open it, it just crushes. It started to happen after IOS 15.7.5 update.
The problem is observed on iPhone 7 running IOS 15.7.5

**Comment by ArtGMlg** [comment]
Okay, somehow it started to work, but I'm still not sure what the problem was in

**Comment by LunarN0v4** [comment]
Close your issue if it's fixed
