### ISSUE TITLE
"Can't Find App Folder! tmp_ipa" and " can't find 'CFBundleIdentifier' " Upon installing Scarlet

### ISSUE THREAD

**Issue by ASDF123214321** [DebianArch64/DebProvision#144]

**Comment by ASDF123214321** [comment]
Listening on :6969
Listening on 127.0.0.1:6970
- Please wait as Scarlet sideloads.
[Generating certificate] ->
←[31m>>> Can't Find App Folder! tmp_ipa
←[0mcan't find 'CFBundleIdentifier'

**Comment by DebianArch64** [comment]
Fixed in the new updates
