### ISSUE TITLE
Failed Installing Scarlet: open ScarletAlpha.ipa: read-only file system

### ISSUE THREAD

**Issue by Yacnamy** [DebianArch64/DebProvision#149]
I don't know what the problem is but when I click on install button it says sideloading scarlet and then this error shows up:
Failed Installing Scarlet: open ScarletAlpha.ipa: read-only file system
what should I do?

**Comment by ooerz** [comment]
i have the same issue

**Comment by DebianArch64** [comment]
Don't run from the DMG
