### ISSUE TITLE
Questions about the app

### ISSUE THREAD

**Issue by Zany-Zachary1** [DebianArch64/DebProvision#15]
So I have a few questions about the app.

1. Where can I get more certs to import?  I just realized that when you press-hold onto the button on the top right, you can manager your certs.
2. Will this ever be on the App Store?  I’m guessing not because apple is retarded and won’t want app installing.
3. What does the little red dot in the top right of the app’s home page mean?  Sometimes it’s green and sometimes orange or red.

Thanks a lot and sorry for the not-issue-issue.

**Comment by DebianArch64** [comment]
> So I have a few questions about the app.
> 
> 1. Where can I get more certs to import?  I just realized that when you press-hold onto the button on the top right, you can manager your certs.
> 2. Will this ever be on the App Store?  I’m guessing not because apple is retarded and won’t want app installing.
> 3. What does the little red dot in the top right of the app’s home page mean?  Sometimes it’s green and sometimes orange or red.
> 
> Thanks a lot and sorry for the not-issue-issue.

Don't worry about it - this is a really good question :)

The colors:
- red -> revoked
- orange -> recently revoked
- blue -> some sort of anti-revoke is enabled
- green -> signed

Cert importing in ScarletCloud is disabled (I have no idea why I decided this) - if you want to import your certificate use normal Scarlet - here is an IPA you can ironically sideload with ScarletCloud https://we.tl/t-bTT4BJ9fuT

This won't be on the AppStore because I'm a really cheap person xD

**Comment by Zany-Zachary1** [comment]
Awesome, thanks man!  I'm sure if you open a Patreon or GoFundMe or something the community would pay for you!

Another thing, I just want to thank you for developing this, you're awesome, and I've met others that think so too.  You should open up a discord server so the community can interact with you guys more!  I could even make the server if you wanna add me.

**Comment by DebianArch64** [comment]
> Awesome, thanks man! I'm sure if you open a Patreon or GoFundMe or something the community would pay for you!
> 
> Another thing, I just want to thank you for developing this, you're awesome, and I've met others that think so too. You should open up a discord server so the community can interact with you guys more! I could even make the server if you wanna add me.

Yeah add me on discord - DebianArch#1935

**Comment by Zany-Zachary1** [comment]
Alright I’m spektacle#3612
