### ISSUE TITLE
Scarlet Installation Fail

### ISSUE THREAD

**Issue by YungChrissi** [DebianArch64/DebProvision#150]
_**Whenever i try to install Scarlet via Mac (i even tried to sudo the scarletcloud) i get the following error:**_

Last login: Wed May 24 19:00:47 on ttys000
chris@Chriss-MBP ~ % sudo /Applications/ScarletCloud.app/Contents/MacOS/scarletcloud
Password:
Listening on :6969
Authorization Result Code: 0
1
Ready for incoming connections...

Connected -> 00008030-000364522104802E
00008030-000364522104802E
Handling response.
response: {"X-Apple-Locale":"en_US", "X-MMe-Client-Info":"<iMac20,2> <Mac OS X;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>", "X-Apple-I-MD-LU":"910CEDC10C683FC578DDA9D3F3CEBD7309FCD92ACFED1359DC4EC893B732DE85", "X-Apple-I-TimeZone":"PST", "X-Apple-I-MD":"AAAABQAAABBAsdKJliloiwHlF+xFjEdtAAAAAQ==", "X-Apple-I-MD-M":"s6l4qaOtOO1Xi7TFInko2QL9amza4TkBKb1ZDnF4w5ebK0Pyt+ys+2dCUg8SIyKvxp4ZqVCMbbuZUdZG", "X-Mme-Device-Id":"8417143E-91D3-5503-8221-7839B2D012FE", "X-Apple-I-Client-Time":"2023-05-24T19:01:13Z", "X-Apple-I-SRL-NO":"C02JJ0U4F897", "X-Apple-I-MD-RINFO":"17106176"}
- Please wait as Scarlet sideloads.
Handling response.
response: {"X-Apple-Locale":"en_US", "X-MMe-Client-Info":"<iMac20,2> <Mac OS X;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>", "X-Apple-I-MD-LU":"910CEDC10C683FC578DDA9D3F3CEBD7309FCD92ACFED1359DC4EC893B732DE85", "X-Apple-I-TimeZone":"PST", "X-Apple-I-MD":"AAAABQAAABBAsdKJliloiwHlF+xFjEdtAAAAAQ==", "X-Apple-I-MD-M":"s6l4qaOtOO1Xi7TFInko2QL9amza4TkBKb1ZDnF4w5ebK0Pyt+ys+2dCUg8SIyKvxp4ZqVCMbbuZUdZG", "X-Mme-Device-Id":"8417143E-91D3-5503-8221-7839B2D012FE", "X-Apple-I-Client-Time":"2023-05-24T19:01:14Z", "X-Apple-I-SRL-NO":"C02JJ0U4F897", "X-Apple-I-MD-RINFO":"17106176"}
00D0A90100700000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode. Input type: PEM
00D0A90100700000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode.  Input type: DER, Input structure: type-specific
00D0A90100700000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode.  Input type: DER, Input structure: PrivateKeyInfo
00D0A90100700000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode. Input type: DER
00D0A90100700000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1188:
00D0A90100700000:error:0688010A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:crypto/asn1/tasn_dec.c:752:
00D0A90100700000:error:0688010A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:685:Field=pkey, Type=PKCS8_PRIV_KEY_INFO
00D0A90100700000:error:068000A7:asn1 encoding routines:d2i_AutoPrivateKey_legacy:unsupported public key type:crypto/asn1/d2i_pr.c:195:
00D0A90100700000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

**Can't Load P12 or PrivateKey File! Please Input The Correct File And Password!
receive packet: ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.lfod3b/extracted/Payload/Scarlet.app : 0xe8008015 (A valid provisioning profile for this executable was not found.))**

_**Is there any way to fix this?**_

**Comment by aldemar360** [comment]
Scarlet no se me descarga qué puedo hacer dígame por favor

**Comment by aldemar360** [comment]
Scarlet no se descarta me aparece en blanco por favor necesito ayuda
