### ISSUE TITLE
problem with scarletcloudux-windows-386 when i open this a gui not open

### ISSUE THREAD

**Issue by Namtheepic** [DebianArch64/DebProvision#151]
when i open scarletcloudux-windows-386 file it only run a cmd and then nothing happen i have tried turn off virus protection but not working

**Comment by Sasukezin678** [comment]
I'm also having this problem

**Comment by DebianArch64** [comment]
Uses OpenGL GUI driver - it ships with all major operating-systems

**Comment by YeeCrimson** [comment]
BRO WHAT THE FUCK ISTHE CLII BUILDddddddddddddddddddddddddddddddddddd
