### ISSUE TITLE
Can't Load P12 or PrivateKey File! Please Input The Correct File And Password!

### ISSUE THREAD

**Issue by kosmosnya** [DebianArch64/DebProvision#152]
Trying to install Scarlet via MacBook on macOS with wired connected device and I get this issue:

Connected -> 00008110-001915921A38401E
00008110-001915921A38401E
Handling response.
response: {"X-Apple-Locale":"en_US", "X-MMe-Client-Info":"<iMac20,2> <Mac OS X;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>", "X-Apple-I-MD-LU":"CEF8C68FC671692330FBBDE4EFD80536651614A47579ADF7CD63FF3AF1751929", "X-Apple-I-TimeZone":"PST", "X-Apple-I-MD":"AAAABQAAABCTyyk6d5TURkmLaJ2co1D4AAAAAQ==", "X-Apple-I-MD-M":"fMPhPimX1gA1StIWGh3ey777W8nIDN5TbvTaA0vV93IhOxWTigO/PzVdJ6Z7sp0i1ZqzgKhDwFgntd+X", "X-Mme-Device-Id":"9303F10B-B4C4-54D7-B673-B749E95C9059", "X-Apple-I-Client-Time":"2023-05-30T10:03:54Z", "X-Apple-I-SRL-NO":"C02GWJQEQ6L4", "X-Apple-I-MD-RINFO":"50660608"}
Handling response.
response: {"X-Apple-Locale":"en_US", "X-MMe-Client-Info":"<iMac20,2> <Mac OS X;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>", "X-Apple-I-MD-LU":"CEF8C68FC671692330FBBDE4EFD80536651614A47579ADF7CD63FF3AF1751929", "X-Apple-I-TimeZone":"PST", "X-Apple-I-MD":"AAAABQAAABCTyyk6d5TURkmLaJ2co1D4AAAAAQ==", "X-Apple-I-MD-M":"fMPhPimX1gA1StIWGh3ey777W8nIDN5TbvTaA0vV93IhOxWTigO/PzVdJ6Z7sp0i1ZqzgKhDwFgntd+X", "X-Mme-Device-Id":"9303F10B-B4C4-54D7-B673-B749E95C9059", "X-Apple-I-Client-Time":"2023-05-30T10:03:57Z", "X-Apple-I-SRL-NO":"C02GWJQEQ6L4", "X-Apple-I-MD-RINFO":"50660608"}
Wrote 001761-08-f5bdd3c9-a6b1-46cf-b507-bfc647ab401e
- Please wait as Scarlet sideloads.
[Generating certificate] ->
00B0C66D01000000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode. Input type: PEM
00B0C66D01000000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode.  Input type: DER, Input structure: type-specific
00B0C66D01000000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode.  Input type: DER, Input structure: PrivateKeyInfo
00B0C66D01000000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto/encode_decode/decoder_lib.c:101:No supported data to decode. Input type: DER
00B0C66D01000000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1188:
00B0C66D01000000:error:0688010A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:crypto/asn1/tasn_dec.c:752:
00B0C66D01000000:error:0688010A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:685:Field=pkey, Type=PKCS8_PRIV_KEY_INFO
00B0C66D01000000:error:068000A7:asn1 encoding routines:d2i_AutoPrivateKey_legacy:unsupported public key type:crypto/asn1/d2i_pr.c:195:
00B0C66D01000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
>>> Can't Load P12 or PrivateKey File! Please Input The Correct File And Password!
receive packet: ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.cJSvgW/extracted/Payload/Scarlet.app : 0xe8008015 (A valid provisioning profile for this executable was not found.))
<img width="1440" alt="Снимок экрана 2023-05-30 в 10 07 51" src="https://github.com/DebianArch64/DebProvision/assets/34073505/332af361-ffbd-46ce-943c-46071db8e2b3">

**Comment by white-r0se** [comment]
Also have this issue

**Comment by DebianArch64** [comment]
This was a fixed a while back, latest OpenSSL versión by default doesn't support legacy encryptions
