### ISSUE TITLE
Scarlet not installing 

### ISSUE THREAD

**Issue by macfixs** [DebianArch64/DebProvision#153]
When i install scarlet on macOS it gives me this message:     error failed installing scarlet:recive packet:ApplicationVerificationFailed(failed to verify code signature of/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.kmr3SU/extracted/payload/scarlet.app:0xe8008015(A valid provisining profile for this executable was not found.)) 

Does anyone know how to fix?

**Comment by the1prodigy** [comment]
![Uploading Screenshot 2023-06-02 at 20.18.34.png…]()

**Comment by MEhdimmz** [comment]
same problem on macOS

>>> Can't Load P12 or PrivateKey File! Please Input The Correct File And Password!

**Comment by heyimdumblol** [comment]
I've got the same problem

**Comment by DebianArch64** [comment]
Duplicate of #150
