### ISSUE TITLE
Just a quick question!

### ISSUE THREAD

**Issue by coolfangamerlolhaha** [DebianArch64/DebProvision#156]
Does anyone know how to use the virtual wifi sync mode? If so thank you!

**Comment by SpektacleFR** [comment]
On Windows and MacOS, you simply have to enable Wifi-Sync in the iTunes program (you do this while your device is plugged in).  After rebooting both devices, open ScarletCloud on your Windows/MacOS machine, and install Scarlet on your iPhone/iPad.  If all goes well, you should have wifi-sync enabled, and working wireless side loads, as long as you are on the same local network.
