### ISSUE TITLE
Ubuntu - Amd64 version- Stucked at “Re-login”

### ISSUE THREAD

**Issue by uphantom89** [DebianArch64/DebProvision#159]
Dear developer,
I’m trying to install scarlet using computer method.
My OS is Ubuntu, I successful  to launch the desktop UI, choose my phone ID, logged in my email and password, entered allow code. But after that, the log screen only show “Relogin ….)

My iphone OS is 15.6.1, XS Max.

Thank you.

**Comment by zeuga1** [comment]
I use Linux too, how do i lunch the UI? because i cant seem to figure out how.

**Comment by snwm69x** [comment]
have the same problem

**Comment by DebianArch64** [comment]
You have to install usbmuxd and have your phone plugged into the computer before you run ScarletCloud

It's a restriction on Linux

**Comment by snwm69x** [comment]
> You have to install usbmuxd and have your phone plugged into the computer before you run ScarletCloud
> 
> It's a restriction on Linux - I'll make sure to make a proper video after the next row of major updates this week
usbmuxd already installed and phone plugged

**Comment by dev-comrade** [comment]
> > You have to install usbmuxd and have your phone plugged into the computer before you run ScarletCloud
> > It's a restriction on Linux - I'll make sure to make a proper video after the next row of major updates this week
> 
> usbmuxd already installed and phone plugged

Hi, show result
`usbmuxd -f` and `sudo ps -aux | grep usbmuxd`

**Comment by snwm69x** [comment]
![photo_2023-10-14_19-49-05](https://github.com/DebianArch64/DebProvision/assets/119750978/6b0783e3-1ab1-4dd1-8751-37abf94e80e7)
