### ISSUE TITLE
usbmux connect: dial tcp 127.0.0.1:27015: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Listlessness** [DebianArch64/DebProvision#160]
usbmux connect: dial tcp 127.0.0.1:27015: connectex: No connection could be made because the target machine actively refused it.

**Comment by DebianArch64** [comment]
This isn't related to Scarletcloud - 27015 is the computers muxer socket port

You need itunes installed for the muxer to exist
