### ISSUE TITLE
"This Apple Id Cannot Be Used For Development With XCode" Wants to be removed

### ISSUE THREAD

**Issue by SalahSabbagh** [DebianArch64/DebProvision#165]
Was was trying to install scarlet without a revoke but This Happend "This Apple ID Cannot Be Used For Development With XCode"

**Comment by DebianArch64** [comment]
This is a message from Apple - they are blocking some apple accounts from being used for install. Try using another one and it should work

**Comment by hyuipelado** [comment]
Oi

**Comment by hyuipelado** [comment]
@hyuipelado

**Comment by hyuipelado** [comment]
![Uploading D80F89ED-EC83-4FA1-8A04-5442966ABE4E.jpeg…]()

**Comment by hyuipelado** [comment]
#139 
```c

``` 
![682246A6-F0CD-445F-9904-C82754798CB6](https://github.com/DebianArch64/DebProvision/assets/115774385/2f61f522-401e-41bb-b758-e7dace29fba8)
