### ISSUE TITLE
Error "Cant Sideload, Searching for wifi devices"

### ISSUE THREAD

**Issue by TvMan-java** [DebianArch64/DebProvision#166]
every time I try to sideload it says cant sideload searching for wifi devices"

**Comment by DebianArch64** [comment]
You need to be connected to your computer for installs

**Comment by musa9995** [comment]
i installed scarlet  successfully with pc on ios 17.1 but when i want to install any ipa or download its say can’t sideload 
searching for wi-fi devices.

**Comment by Vineelakula1** [comment]
Same problem can you please help me out of this 🤧

**Comment by DebianArch64** [comment]
> Same problem can you please help me out of this 🤧

You need to be connected to the computer in some sort of fashion or enable wireguard

**Comment by simox767** [comment]
how do i set up wireguard

**Comment by musa9995** [comment]
install and try with same wifi connection pc and mobile then its work

**Comment by simox767** [comment]
but i have to do it from pc or phone

**Comment by Arschpirat** [comment]
I'm stuck at 59% when I download ipa's

**Comment by Mikeyman2012** [comment]
> > Same problem can you please help me out of this 🤧
> 
> 
> 
> You need to be connected to the computer in some sort of fashion or enable wireguard 

I do have my phone plugged in but it still says the same problem

**Comment by stainthemighty** [comment]
same issue, I am connected to the pc and both iTunes and 3Utools can see the phone (iphone 15+) and I've even loaded the files I'm trying to install into the Scarlet>documents folder, so I'm trying to sideload the ipas directly from the device, still get error "Searching for wifi devices". Please help
