### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by LLuanZZ** [DebianArch64/DebProvision#167]
Bro, I went to install an IPA through ScarletCloud but this error appeared, how do I solve it? Thank you in advance for this platform that you have created.

![4B3E4133-8FAE-42E1-8D38-284DA7FB7A10](https://github.com/DebianArch64/DebProvision/assets/108953018/98674855-2ca6-46d9-a745-9bab113d23bc)

**Comment by DebianArch64** [comment]
No longer exists
