### ISSUE TITLE
Issue with downloading scarlet from the GUI

### ISSUE THREAD

**Issue by Cody990** [DebianArch64/DebProvision#168]
I have connected my device and downloaded icloud and itunes on my laptop 
I have windows 10 with 32-bit

When I load up the windows file I get this:

Listening on :6969
Waiting for device to be connected...
Connected -> 00008103-0005404E3CD4401D
Use the arrow keys to navigate: ↓ ↑ → ←
? Select Action:
  > Connect
    (re)install Scarlet
Listening on 127.0.0.1:6970

what do I do now? I press an an arrow key or enter :

Listening on :6969
Waiting for device to be connected...
Connected -> 00008103-0005303E3CE3401E
Use the arrow keys to navigate: ↓ ↑ → ←
v Connect

someone help please

**Comment by han9over** [comment]
use arrow key and selected (re)install Scarlet. It's failing with different error for me, but atleast that's how you navigate. Or just use the GUI version to be easier.

**Comment by DebianArch64** [comment]
> use arrow key and selected (re)install Scarlet. It's failing with different error for me, but atleast that's how you navigate. Or just use the GUI version to be easier.

To add on this, use connect option only if you already have the scarlet app installed on your device and use the install option to install it
