### ISSUE TITLE
Rocket Instagram

### ISSUE THREAD

**Issue by Be8947** [DebianArch64/DebProvision#171]
I use Scarlet for the Youtube, bu saw some people installing Rocket Instagram, but for me it doesn't appear. Can you please put Rocket Ipa on Scarlet?

**Comment by SpektacleFR** [comment]
Doubt this will happen, as you can just download Rocket Instagram from online.

Link for an active GitHub: https://github.com/purp0s3/Tweaked-iOS-Apps/releases
