### ISSUE TITLE
maximum amount of devices reached for your id

### ISSUE THREAD

**Issue by Arman-Taggar** [DebianArch64/DebProvision#172]
how to remove ids

**Comment by DebianArch64** [comment]
You can't remove devices from your apple account

**Comment by Arman-Taggar** [comment]
What to do now!?

**Comment by Arman-Taggar** [comment]
Do i have make a new id and can it work on same phone with same apple id

**Comment by DebianArch64** [comment]
> Do i have make a new id and can it work on same phone with same apple id

Yes you can make a temporary apple account just for app installs and it'll work fine - keep in mind to not make new accounts often for installs because there is also a limit to how many accounts can be associated to your device
