### ISSUE TITLE
Blocked apple id account 

### ISSUE THREAD

**Issue by TamirRothschild** [DebianArch64/DebProvision#175]
its seems every time i use the tool, apple blocks my account, i then have to unlock it and change the password.
i think the requestor is broken or apple may have blacklisted it as the last time i used the tool it did work

**Comment by DebianArch64** [comment]
> its seems every time i use the tool, apple blocks my account, i then have to unlock it and change the password. i think the requestor is broken or apple may have blacklisted it as the last time i used the tool it did work

There is only one way to login there is no wrong or right. Apple GSA API is used it's the same API that apple uses in xcode
