### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Listlessness** [DebianArch64/DebProvision#176]
Listening on :6969
usbmux connect: dial tcp 127.0.0.1:27015: connectex: No connection could be made because the target machine actively refused it.
Press [ENTER] to terminate

Installed Icloud and Itunes not from the windows 11 store

**Comment by Listlessness** [comment]
?

**Comment by DebianArch64** [comment]
This has nothin to do with ScarletCloud - it means no usbmuxd drivers are installed meaning iTunes isn't installed properly
