### ISSUE TITLE
Failed Installing Scarlet: failed with status: 403 (https://resources.usescarlet.com/api/sign?beta=30)

### ISSUE THREAD

**Issue by effevalli5909** [DebianArch64/DebProvision#177]
scarlet is giving me error 403 while trying to install on iPhone XR on iOS 16.6

**Comment by CatchMe-Plz** [comment]
Anything on this error because i am getting same error when i click on install scarlet. This error shows up in cmd.

**Comment by CatchMe-Plz** [comment]
@DebianArch64

**Comment by DebianArch64** [comment]
Fixed on the latest update, changelog also has 10 features added
