### ISSUE TITLE
failed to get anisette 

### ISSUE THREAD

**Issue by Dogo69Dog** [DebianArch64/DebProvision#179]
![Screen Shot 2023-08-28 at 5 12 45 PM](https://github.com/DebianArch64/DebProvision/assets/143454412/fee4a278-af23-42e8-8748-1339c264d191)

Getting some issue when trying to install scarlet cloud. Please lmk how to fix

**Comment by Rcbye426** [comment]
redownload it to make it work or run it as adminstrater

**Comment by Dogo69Dog** [comment]
I tried re downloading it and it didn't work, I look in main and I see that its not installing its mail plugin and I'm also on mac

**Comment by Dogo69Dog** [comment]
> redownload it to make it work or run it as adminstrater

Just did it on windows and it doesent  work, same error

**Comment by DebianArch64** [comment]
Bunch of changes since August, closing as fixed
