### ISSUE TITLE
Scarlet requirements on Windows

### ISSUE THREAD

**Issue by DodoGames7** [DebianArch64/DebProvision#182]
What do i need to have installed to be able to use Scarlet on Windows to connect to my iPhone? I have tried to use CLI and the GUI and they do not work. The GUI generates errors so quick that i'm unable to read them as the program closes after that. For the CLI one, it does nothing when you choose install or connect at all. I have been struggling to get this to work for a while.

Also, i have iTunes and iCloud installed as well so i'm not sure on why it does not work for me.

**Comment by Dilfy9tik** [comment]
if you figure it out can you let me know? I have it on my phone but for some reason cant get it on the pc.

**Comment by SpektacleFR** [comment]
Running it through a CMD window should allow you to copy errors after it closes.  If you can copy them, please paste them here and we'll take a look.

**Comment by DodoGames7** [comment]
That's the thing, running the GUI one opens the CMD window but closes quickly for the same reason mentioned above

**Comment by SpektacleFR** [comment]
Open CMD and make it output anything to a text file - you can do that like this:
`start scarletcloudux.exe > log.txt`
Then go ahead and paste that text file or use a pastern link if it's too big :)

**Comment by DodoGames7** [comment]
I tried that, it doesn't work with both normal and administrator for some reason.

**Comment by DodoGames7** [comment]
However, i managed to capture a screenshot of one the log errors for this.
![image](https://github.com/DebianArch64/DebProvision/assets/69091682/5094b74e-fcc1-4b8c-a2bf-7ae35e5df55d)

**Comment by SpektacleFR** [comment]
@DebianArch64 any ideas?

**Comment by DebianArch64** [comment]
Yeah, ScarletCloud GUI uses fyne V3, which is built from OpenGL - if a computer doesn't have it, it should work after it's installed

**Comment by DodoGames7** [comment]
> Yeah, ScarletCloud GUI uses fyne V3, which is built from OpenGL - if a computer doesn't have it, it should work after it's installed

How do you install that may i ask?

**Comment by DebianArch64** [comment]
> > Yeah, ScarletCloud GUI uses fyne V3, which is built from OpenGL - if a computer doesn't have it, it should work after it's installed
> 
> How do you install that may i ask?

Update your graphics driver's or install OpenGL compatibility pack on the Microsoft store

In the case that your graphics card just doesn't support this version you can use the CLI builds:
https://github.com/DebianArch64/DebProvision/releases/tag/CLI

**Comment by DebianArch64** [comment]
Closing iCloud and iTunes required. iTunes for device detection and iCloud to legally use DLLs to handle anisette generation for secure login

If you have crashes it's likely that you don't have a computer with modern graphics, download this DLL below and place it in the same location as ScarletCloud exe
https://downloads.fdossena.com/geth.php?r=mesa-latest
