### ISSUE TITLE
Anisett is empty(server error) Windows

### ISSUE THREAD

**Issue by Chaitya2** [DebianArch64/DebProvision#184]
![Error](https://github.com/DebianArch64/DebProvision/assets/145338256/72d5ec21-d684-4309-a72d-755795d15ab1)
What should I do about this

**Comment by aunwho** [comment]
> > ![Error](https://user-images.githubusercontent.com/145338256/272558586-72d5ec21-d684-4309-a72d-755795d15ab1.png) What should I do about this
> 
> Check the black window - if it says iCloud not found install iCloud, if it says iTunes not found install iTunes
> 
> Links to both are on the GitHub, they can't be from the Microsoft store

**but I have them both downloaded**
