### ISSUE TITLE
Redirecting to MUX

### ISSUE THREAD

**Issue by Drakens87** [DebianArch64/DebProvision#187]
Hi oh!
Can someone explain to me why my installations remain stuck at 74% with this error?
iPhone XR 16.6.1 - Win 10 64b

`[1] Redirecting '50480' to mux`

Did I miss something?
Thank you so much!

**Comment by DebianArch64** [comment]
> Hi oh! Can someone explain to me why my installations remain stuck at 74% with this error? iPhone XR 16.6.1 - Win 10 64b
> 
> `[1] Redirecting '50480' to mux`
> 
> Did I miss something? Thank you so much!

If you're using an older version of ScarletCloud give it an update and hit "Install Scarlet" - this'll update over your current Scarlet

The wired installs can take a hot minute compared too, it's better to be on the same wifi network as the computer to do installs or use wireguard for computerless

**Comment by a1lann** [comment]
I got the exact same problem, stuck at 60% "redirecting "60081" to mux
Iphone 12 pro max iOS 17.0.1 - Win 10 64b
I already made update and I'm waiting since like 5 minutes with 60% stuck to add snapchat to scarlet

**Comment by DebianArch64** [comment]
> I got the exact same problem, stuck at 60% "redirecting "60081" to mux Iphone 12 pro max iOS 17.0.1 - Win 10 64b I already made update and I'm waiting since like 5 minutes with 60% stuck to add snapchat to scarlet

I'll make sure to look into this, send over the URL to the IPA - in the meantime enable Wireguard, so the device can handle the install directly or you can disable apple's wifi-sync in iTunes so that my replacement "virtual wifi-sync" can go into effect:
https://x.com/DebianArch/status/1709724249202528670?s=20

**Comment by a1lann** [comment]
I just installed Wireguard and tried again and It worked tysm!!! (maybe the first who had this problem should try it if they didn't already)

**Comment by DebianArch64** [comment]
![Screenshot_20231013-083705](https://github.com/DebianArch64/DebProvision/assets/63203414/a247a247-e341-4fa1-86fe-d564dd92bf53)

If it gets stuck at 60% when installing then it gets stuck either during the actual install process or at the very end of writing the files - I should be able to take a look on both parts today to see what I have to change to fix it

I'll close this issue once an update is pushed for it

**Comment by a1lann** [comment]
mine is solved bc when I tried it first I didn’t download Wireguard, once you answered to my first message, I installed it and tried downloading snapchat again with scarlet and It worked. I think the first person that opened this issue might have the same problem and they should install Wireguard and follow your tutorial to solve it because it worked that way for me.

**Comment by RudeBoy4RomUA** [comment]
I got this:
Device redirect ->
[1] Redirecting '50058' to mux

And all the apps got stuck at 60, and 75%
It has something to do with the latest apple update, I bet

**Comment by Cusop** [comment]
Me too

**Comment by Nastyusha23** [comment]
wireguard not help(( 
maybe the iPhone update is really to blame?

**Comment by kassoolo** [comment]
> > Hi oh! Can someone explain to me why my installations remain stuck at 74% with this error? iPhone XR 16.6.1 - Win 10 64b
> > `[1] Redirecting '50480' to mux`
> > Did I miss something? Thank you so much!
> 
> If you're using an older version of ScarletCloud give it an update and hit "Install Scarlet" - this'll update over your current Scarlet
> 
> The wired installs can take a hot minute too, it's better to be on the same wifi network as the computer to do installs or use wireguard for computerless
> 
> * once on my own computer I ran into something similar I forgot how I fixed it on my end it was either an update I pushed or I restarted my computer

thank you it worked!

**Comment by brandodt** [comment]
> > I got the exact same problem, stuck at 60% "redirecting "60081" to mux Iphone 12 pro max iOS 17.0.1 - Win 10 64b I already made update and I'm waiting since like 5 minutes with 60% stuck to add snapchat to scarlet
> 
> I'll make sure to look into this, send over the URL to the IPA - in the meantime enable Wireguard like in the video, so the device can handle the install directly or you can disable apple's wifi-sync in iTunes so that my replacement "virtual wifi-sync" can go into effect: https://x.com/DebianArch/status/1709724249202528670?s=20

Wireguard works for me, but do i need to refresh the app every 7 days because it is said on the expiration on the ipa that i just installed

**Comment by enkl1n** [comment]
if the method is computer-based, where do you need to install wireguard for phone or for computer?

**Comment by RudeBoy4RomUA** [comment]
> if the method is computer-based, where do you need to install wireguard for phone or for computer?

So, you need any VPN, not wireguard in particular, on your iphone

**Comment by enkl1n** [comment]
unfortunately, even with VPN enabled, I get this error

**Comment by DebianArch64** [comment]
Any VPN will not work, Wireguard is an app that allows developers to make a configuration file to setup their own advanced networks. This is used to create a fake IP on the device that it can contact itself through, meaning no computer required installs

Install wireguard and import the EMP.conf file everything will work fine after

**Comment by mvpilica99** [comment]
mine is also getting stuck on 60 or 59 % i tried wireguard and the first time it did work now its not working its the same could you please help thanks

**Comment by mvpilica99** [comment]
> unfortunately I'm a kettle and I don't know how to do it on my phone, I can't figure out how to use wireguard(

once you install wireguard you will need to download emp for wireguard to do that just go on safari and search emp wireguard download it from github and open wireguard then add that file to wireguard and turn emp on now you should be able to download ipa files

**Comment by puppiebite** [comment]
just in case anyone has the same problem i've been having, once you connect with wireguard make sure you disconnect from your pc or else it won't download

**Comment by xmaloo** [comment]
https://www.reddit.com/r/sideloaded/comments/174vwjc/problem_with_scarlet/?sort=new. Use this reddit guide it works. DONT USE ANY VPN

**Comment by COMPLEXWASTAKEN** [comment]
mine was fixed on a phone reboot
