### ISSUE TITLE
wont let me open scarletcloud on windows

### ISSUE THREAD

**Issue by FIXERORPIXAR** [DebianArch64/DebProvision#19]
its says usbmux connect : no connection

**Comment by DebianArch64** [comment]
> its says usbmux connect : no connection

Make sure iTunes and iCloud are installed from Apples website and not the Microsoft store - iTunes is needed for USB communication and iCloud is used for native anisette

**Comment by FIXERORPIXAR** [comment]
usbmux connect: dial tcp 127.0.0.1:27015: connectex: No connection could be made because the target machine actively refused it. thats what it says

**Comment by FIXERORPIXAR** [comment]
also ihave itunes and i cloud installed

**Comment by DebianArch64** [comment]
> usbmux connect: dial tcp 127.0.0.1:27015: connectex: No connection could be made because the target machine actively refused it. thats what it says

Sounds like a permission issue - try running it as admin or disabling an anti-virus

Also make sure both iTunes and iCloud are installed from apples website and not the microsoft store
