### ISSUE TITLE
FAILED REFRESHING, Re-authentication required 

### ISSUE THREAD

**Issue by gunpreetlakesar** [DebianArch64/DebProvision#192]
@DebianArch64 Please See This Issue In Latest Scarlet I installed today.

![IMG_4764](https://github.com/DebianArch64/DebProvision/assets/148060540/a44a1b0b-63a0-4d3f-b876-afd2934a2f2a)

**Comment by DebianArch64** [comment]
> @DebianArch64 Please See This Issue In Latest Scarlet I installed today.
> 
> ![IMG_4764](https://user-images.githubusercontent.com/148060540/276577045-a44a1b0b-63a0-4d3f-b876-afd2934a2f2a.png)

Looks normal, anytime this error happens the Scarlet app automatically uses the stored email and password to regenerate the tokens

If you have changed your email or password since try logging out by 3D touching the sideload button then hitting "Log out"

**Comment by gunpreetlakesar** [comment]
when i tap on refresh they send me verification code but where i fill this verification code??

![IMG_4769](https://github.com/DebianArch64/DebProvision/assets/148060540/e48d049a-048f-4c90-b08e-3b9c3b605b87)

**Comment by gunpreetlakesar** [comment]
After verification, When i try to refresh they again show me this.

![IMG_4770](https://github.com/DebianArch64/DebProvision/assets/148060540/d884daef-34f9-4791-a534-c3bc940acdad)

**Comment by DebianArch64** [comment]
> when i tap on refresh they send me verification code but where i fill this verification code??
> 
> ![IMG_4769](https://user-images.githubusercontent.com/148060540/276622902-e48d049a-048f-4c90-b08e-3b9c3b605b87.png)

After you press ok you'll see a prompt to enter a 2FA code

**Comment by gunpreetlakesar** [comment]
> @DebianArch64 After verification, When i try to refresh they again show me this.
> 
> ![IMG_4770](https://user-images.githubusercontent.com/148060540/276623953-d884daef-34f9-4791-a534-c3bc940acdad.png)

@DebianArch64 I got 2FA prompt But After that when i click Refresh it Says Failed Refreshing.

**Comment by gunpreetlakesar** [comment]
@DebianArch64 Reply??

**Comment by SpektacleFR** [comment]
@gunpreetlakesar He will reply when he has the chance, there's no need to ping him.

**Comment by Akramx15** [comment]
so i have the same error and when i refresh scarlet app i got new icon for scarlet  and i can't press i am on ios 16.6 iphone 13

**Comment by Akramx15** [comment]
oh i fix it just sing out and log in in scarlet app and its work

**Comment by Akramx15** [comment]
but the scarlet app still have the same error when you refresh the app you will have 2 scarlet app and you can't press it
