### ISSUE TITLE
Re-authen required error and scarlet refresh

### ISSUE THREAD

**Issue by tmnphu2210** [DebianArch64/DebProvision#194]
I refresh youtube but it showed the error like this
![FC8CDD41-4042-4518-B96A-B4716AAD690C](https://github.com/DebianArch64/DebProvision/assets/59415928/4fc35cde-8d6c-4159-8f21-d151f5081ccc)

And when I install any app from Home tab, I can refresh again. 
Also, Scarlet after refresh created 2 app icon in list. And I cannot touch in it to view the remaining day.

**Comment by tmnphu2210** [comment]
Close, duplicate

**Comment by Akramx15** [comment]
how to fix it

**Comment by smashingbunny149** [comment]
im getting same error donno what to do,scarlet created 2 icons after refreshing,not responsive ,im unable to refresh remaining apps

**Comment by Akramx15** [comment]
> im getting same error donno what to do,scarlet created 2 icons after refreshing,not responsive ,im unable to refresh remaining apps

Just install TrollStore and all your problems will solve

**Comment by smashingbunny149** [comment]
I dont know how to install troll store

**Comment by smashingbunny149** [comment]
17.2.1

**Comment by Akramx15** [comment]
> 17.2.1

Sorry your phone not supports TrollStore

**Comment by smashingbunny149** [comment]
why

**Comment by Akramx15** [comment]
![Uploading IMG_0716.png…]()

**Comment by Akramx15** [comment]
![IMG_0716](https://github.com/DebianArch64/DebProvision/assets/149894533/08cbd192-ffcf-4fa5-828f-20d189eed4f8)

**Comment by smashingbunny149** [comment]
ok thanks for the info
