### ISSUE TITLE
Can’t Log-In (Scarlet)

### ISSUE THREAD

**Issue by gunpreetlakesar** [DebianArch64/DebProvision#195]
@DebianArch64
This problem occurs and my wireguard is not Connecting to Scarlet.
SOLUTION PLEASE 🙏🏻

![IMG_5509](https://github.com/DebianArch64/DebProvision/assets/148060540/c5165f76-8411-4bd5-a94d-af01221d60b9)

**Comment by gunpreetlakesar** [comment]
I have downloaded the scarlet with scarlet cloud computer method

**Comment by tmnphu2210** [comment]
Try pressing/3d touch on sideload icon in top right, sign out.

**Comment by gunpreetlakesar** [comment]
> Try pressing/3d touch on sideload icon in top right, sign out.

 I tried this many time doesn’t help me

**Comment by DebianArch64** [comment]
> > Try pressing/3d touch on sideload icon in top right, sign out.
> 
> I tried this many time doesn’t help me

If this says mismatched environment delete the adi files. They are inside the Scarlet folder in the files app

**Comment by gunpreetlakesar** [comment]
> > > Try pressing/3d touch on sideload icon in top right, sign out.
> > 
> > 
> > I tried this many time doesn’t help me
> 
> If this says mismatched environment delete the adi files. They are inside the Scarlet folder in the files app


but scarlet folder is already empty

**Comment by DebianArch64** [comment]
> > > > Try pressing/3d touch on sideload icon in top right, sign out.
> > > 
> > > 
> > > I tried this many time doesn’t help me
> > 
> > 
> > If this says mismatched environment delete the adi files. They are inside the Scarlet folder in the files app
> 
> but scarlet folder is already empty

I updated my message again

**Comment by gunpreetlakesar** [comment]
@DebianArch64 Help!!

![IMG_5636](https://github.com/DebianArch64/DebProvision/assets/148060540/adf9d51c-c844-4d03-9cb2-fe826cab4bc7)
