### ISSUE TITLE
Didnt get the AnisettePlugin When downloading scarletcloud on mac

### ISSUE THREAD

**Issue by fishfoodisgood** [DebianArch64/DebProvision#199]
I followed the youtube video and It showed that you got the mail plugin by opening scarletcloud package, but when I did it, It didnt pop up a option for me to get the plugin and add the mail plugin to my mail. I deleted it multiple times but that still didn't work

**Comment by J22juice** [comment]
Having the same issue.

**Comment by DebianArch64** [comment]
Mac Sonoma doesn't require the plugin and finding the plugin isn't related to ScarletCloud but MacOS 

- run this command if not on Sonoma:
sudo defaults write "/Library/Preferences/com.apple.mail" EnableBundles -bool YES

**Comment by J22juice** [comment]
![Screen Shot 2023-11-16 at 8 40 30 PM](https://github.com/DebianArch64/DebProvision/assets/151108354/fc6ce073-bef5-4e61-a984-05592ec84747)
The command did make the mail plugin menu show up. But I still can't get the plugin to show. I ran the scarletcloud executable like in the video.
