### ISSUE TITLE
Scarlet Always Crash (Wireguard Wireless Mode)

### ISSUE THREAD

**Issue by NolPixel** [DebianArch64/DebProvision#200]
I try the Wireguard method but when installing the IPA, Scarlet always crash and failed to install.  

Device:
iPhone 11 64 GB (iOS 16.5)

**Comment by strwbzzy** [comment]
I also have the same issue, Scarlet crashes no matter what IPA i tried to sideload. Occurred at 75% of the installation.

Device: 
iPhone X 64 GB (iOS 16.1.2)

**Comment by DebianArch64** [comment]
If using wireguard this'll never occur
