### ISSUE TITLE
Unable to Verify app

### ISSUE THREAD

**Issue by Jedyss** [DebianArch64/DebProvision#201]
I was followed step by step but isnt does working at all hmm

**Comment by Jedyss** [comment]
Help me sir

**Comment by DebianArch64** [comment]
This is not related to the computer method, if you are using Scarlet direct that's the apple blacklist message

**Comment by Jedyss** [comment]
Sir sorry,i was excited to text you🥹

**Comment by DebianArch64** [comment]
> Sir sorry,i was excited to text you🥹

Nothing to be sorry about we can message on discord :D "debianarch"

**Comment by Jedyss** [comment]
Can you teach me how verify this app on ip bcs i relly need this app..i was do anything to verify this app but im fail😭😭

**Comment by Jedyss** [comment]
Accept me sir in discord(jedys28)..i want talk woth you bcs i feel very excited i can talk with people in another county😆
