### ISSUE TITLE
windows installer issue

### ISSUE THREAD

**Issue by nektodon** [DebianArch64/DebProvision#202]
after i successfully installed iTunes and continue installing iCloud from the file provided at main github page i get the error messege
"There is a problem with Windows Installer package a program run as part of the setup did not finish as expected. Contact your support personel or package vendor". Installing from the store seems fine, but when i try to install scarlet and after i fill in login and password, i get the message that icloud is not found.
![image](https://github.com/DebianArch64/DebProvision/assets/149730318/36129e27-e34e-4bce-9436-d8919b2477d6)

**Comment by nektodon** [comment]
should also mention if i install icloud from the microsoft store and try to install scarlet there is no GUI for login and pass, only command prompt window where i can fill in the information.

**Comment by DebianArch64** [comment]
Only the non-microsoft store versions will work because the DLLs aren't obfuscated

**Comment by nektodon** [comment]
yes non-microsoft version give me this error

**Comment by DebianArch64** [comment]
![image](https://github.com/DebianArch64/DebProvision/assets/63203414/ba2be803-378c-4e42-94a7-8caf1f98cae0)
Try updating Net framework

**Comment by n1ckplays** [comment]
same issue for me updated .net frame work didn't help

**Comment by n1ckplays** [comment]
pls tell how to fix

**Comment by EmptyIncject** [comment]
Hi i have some issue going on on scarlet, I logged and followed everything, after that when i tried to download something with my IPA file it shows this : (Sideload error) ![image](https://github.com/DebianArch64/DebProvision/assets/144935214/c669ebf3-7698-42b6-9966-06f7961a1963)

**Comment by DebianArch64** [comment]
Computer methods only work with a connection to usbmuxd

Use wireguard or have your phone plugged into the computer with ScarletCloud opebed
