### ISSUE TITLE
Scarlet app is not installing on iphone

### ISSUE THREAD

**Issue by Fahadopwin** [DebianArch64/DebProvision#203]
"Failed pairing: receive packet: PasscodeRequired"
Whenever i try to install Scarlet app i get this message can anyone help me?
i am also not getting any message on my iphone.

**Comment by DebianArch64** [comment]
> "Failed pairing: receive packet: PasscodeRequired" Whenever i try to install Scarlet app i get this message can anyone help me? i am also not getting any message on my iphone.

You need a passcode enabled on your phone

**Comment by ablissfulrose** [comment]
i dont have a passcode
