### ISSUE TITLE
Installing stucks at 60% on Mac

### ISSUE THREAD

**Issue by sndsxv** [DebianArch64/DebProvision#209]
I have macOS Sonoma and IOS 17.1.1. I tried to install multiple files but they all get stuck at 60%

**Comment by DebianArch64** [comment]
Use wireguard instead of wireless/wired connection

**Comment by sndsxv** [comment]
I tried but it's also not working

**Comment by DebianArch64** [comment]
Is ScarletCloud closed out of too, sometimes the phone connects to it that way

**Comment by DebianArch64** [comment]
> And what should I do?

Make sure only wireguard is available because through wireguard the device is able to contact itself directly for an install other than that no clue shouldn't be able to freeze I just use libimobiledevice framework

**Comment by sndsxv** [comment]
Ok, I will try again later with WIFi!
