### ISSUE TITLE
Cant achive scarlet installation

### ISSUE THREAD

**Issue by joacodru** [DebianArch64/DebProvision#21]
![image](https://user-images.githubusercontent.com/31075448/184065128-7f89b297-7882-421a-801a-72aa216cb948.png)
I did achieve to this point but then nothing happens!!

**Comment by DebianArch64** [comment]
> ![image](https://user-images.githubusercontent.com/31075448/184065128-7f89b297-7882-421a-801a-72aa216cb948.png) I did achieve to this point but then nothing happens!!

Can you give me more info on Twitter @GetScarlet - also try the newer version of ScarletCloud I pushed today - it should have fixed a handful of issues
