### ISSUE TITLE
Cant Install more than 3 Apps (Free Developer Account)

### ISSUE THREAD

**Issue by NMWplays** [DebianArch64/DebProvision#214]
I installed the PC Version of Scarlet and WireGuard but after i installed three Apps Scarlet said "This device hast reached the maximum number of installed apps using a free Developer Profile".
![IMG_20231209_173843](https://github.com/DebianArch64/DebProvision/assets/153382862/6fa80785-1f07-4e2d-8701-43577c402c41)

**Comment by DebianArch64** [comment]
This has nothing to do with Scarlet

**Comment by NMWplays** [comment]
But If i would have a paid Developer Account i would have

**Comment by DebianArch64** [comment]
> But If i would have a paid Developer Account i could have more than three Apps right?

Yes, but it's not recommended to use the computer method with paid developer accounts since the normal version of Scarlet supports them without needing wireguard or anything else

https://docs.usescarlet.com/scarlet/certificates-developer-login
