### ISSUE TITLE
Fyne Error

### ISSUE THREAD

**Issue by davitoso** [DebianArch64/DebProvision#215]
![Annotazione 2023-12-09 221945](https://github.com/DebianArch64/DebProvision/assets/129310417/6de6f71a-f150-4981-a642-779a4bc651ea)

**Comment by DebianArch64** [comment]
OpenGL is a driver that ships with windows machines. Your graphics card doesn't seem to support new graphics

Download this DLL and place it in same location as ScarletCloud 
https://downloads.fdossena.com/geth.php?r=mesa-latest
