### ISSUE TITLE
Searching for Wi-Fi devices.

### ISSUE THREAD

**Issue by docgamesyb** [DebianArch64/DebProvision#219]
hello, recently I wanted to test Scarlet but with its method on computer (Scarlet Cloud) and everything went as planned.
But unfortunately when I'm in the app and I try to install an app (with Scarlet repo or me ipa) it doesn't work it gives me this error message.

(currently the phone version is revoked)

![IMG_3152](https://github.com/DebianArch64/DebProvision/assets/114883208/fdb0d1a2-1314-4b4c-afa1-5e0ad887ec3d)

**Comment by Osaim** [comment]
Keep scarlet running on ur pc
