### ISSUE TITLE
error no response...

### ISSUE THREAD

**Issue by Samhenry7** [DebianArch64/DebProvision#22]
![Capture d’écran 2022-08-11 120925](https://user-images.githubusercontent.com/111027104/184179645-481ab5b7-0415-43a7-8d67-0d11c13ad4e8.jpg)

**Comment by DebianArch64** [comment]
> ![Capture d’écran 2022-08-11 120925](https://user-images.githubusercontent.com/111027104/184179645-481ab5b7-0415-43a7-8d67-0d11c13ad4e8.jpg)

Your computer seems to be blocking ScarletCloud from contacting Apple - try running it as admin

**Comment by Samhenry7** [comment]
how can i running my computer as admin?

**Comment by Zany-Zachary1** [comment]
Run the program as admin lol right click and select "Run as Admin"
