### ISSUE TITLE
Terminated...

### ISSUE THREAD

**Issue by Jynxiethan** [DebianArch64/DebProvision#224]
Can someone help me fix this. every time I open or try reinstalling scarlet, it prompts me with this message " No connection could be made because the target machine actively refused it " anytime I open it. if you know how to fix this please let me  know. Thank you!
![Screenshot 2024-01-06 195503](https://github.com/DebianArch64/DebProvision/assets/155857419/8f1a42c9-7aa3-4fb7-9b8a-0f6b47140068)

**Comment by DebianArch64** [comment]
This is related to iTunes, make sure it's not from the Microsoft store link is on the main page of this GitHub

27015 is a port opened by iTunes for usbmuxd connections if it's not available then iTunes isn't working properly

**Comment by Jynxiethan** [comment]
> This is related to iTunes, make sure it's not from the Microsoft store link is on the main page of this GitHub
> 
> 27015 is a port opened by iTunes for usbmuxd connections if it's not available then iTunes isn't working properly

Thank You Its Working Now!
