### ISSUE TITLE
Error When Trying To Download Apps

### ISSUE THREAD

**Issue by Jynxiethan** [DebianArch64/DebProvision#225]
After downloading scarlet to my phone through my computer, it works perfect! Until I try downloading something. All goes good until I notice it being stuck at 59% on my phone. So I look at scarlet cloud on my computer and it says " error reading: EOF " and now the last thing that comes up on scarlet cloud is " [1] Redirecting '51384' to mux." Does anyone know what this means/causes this? And if so are you able to help fix the problem? Thank you for your help!

**Comment by DebianArch64** [comment]
Download wireguard from the AppStore then import this file, you won't need a computer anymore 
https://github.com/DebianArch64/DebProvision/releases/download/GUI/emp.conf

**Comment by Jynxiethan** [comment]
> Download wireguard from the AppStore then import this file, you won't need a computer anymore https://github.com/DebianArch64/DebProvision/releases/download/GUI/emp.conf

So download wireguard, import the file, and download scarlet on my phone without scarlet cloud?

**Comment by DebianArch64** [comment]
> > Download wireguard from the AppStore then import this file, you won't need a computer anymore https://github.com/DebianArch64/DebProvision/releases/download/GUI/emp.conf
> 
> So download wireguard, import the file, and download scarlet on my phone without scarlet cloud?

You already have scarlet from ScarletCloud, only thing wireguard does is make the computer method work without a computer

**Comment by Jynxiethan** [comment]
> > > Download wireguard from the AppStore then import this file, you won't need a computer anymore https://github.com/DebianArch64/DebProvision/releases/download/GUI/emp.conf
> > 
> > 
> > So download wireguard, import the file, and download scarlet on my phone without scarlet cloud?
> 
> You already have scarlet from ScarletCloud, only thing wireguard does is make the computer method work without a computer

okay thank you, im new to this and just trying to learn.
