### ISSUE TITLE
Anisette is empty (server error)

### ISSUE THREAD

**Issue by Jakuber** [DebianArch64/DebProvision#228]
![chrome_jVMTsSQUDC](https://github.com/DebianArch64/DebProvision/assets/46703461/489515d6-bf5c-4734-8fb6-7bcc9dcddf91)

Hey! Im getting this anisette error, I have both icloud and iTunes installed and logged. I don't have them from Microsoft store, but from .exe

What should I do now please?

**Comment by Jakuber** [comment]
I tried it with my pc and laptop. Also tried with different iPhone device..

**Comment by reeky92** [comment]
can you help me set up native anisette?

**Comment by DebianArch64** [comment]
> ![chrome_jVMTsSQUDC](https://private-user-images.githubusercontent.com/46703461/298283126-489515d6-bf5c-4734-8fb6-7bcc9dcddf91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTYyNzYsIm5iZiI6MTcwNTc5NTk3NiwicGF0aCI6Ii80NjcwMzQ2MS8yOTgyODMxMjYtNDg5NTE1ZDYtYmY1Yy00NzM0LThmYjYtN2JjYzlkY2RkZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAwMTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZDg4NGJjN2IwMDlhOTIyMTdhZDJhNjliOTJiYTFjMjRhMDMyY2ZlYzIyNjU3MmYxNWMyOTNhNTc3NDNjN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sOLYOt_DDgOWzc3T4XCOaAWi0yhu_cwfKEGGtsLAhcw)
> 
> Hey! Im getting this anisette error, I have both icloud and iTunes installed and logged. I don't have them from Microsoft store, but from .exe
> 
> What should I do now please?

It doesn't matter if your logged into iTunes or iCloud
Delete the adi files here they got invalidated, open iTunes after they are deleted 
C:\ProgramData\Apple Computer\iTunes\adi
