### ISSUE TITLE
error : Your development team has reached the maximum number of registered iPhone devices

### ISSUE THREAD

**Issue by liqup** [DebianArch64/DebProvision#229]
Your development team has reached the maximum number of registered iPhone devices
![image](https://github.com/DebianArch64/DebProvision/assets/64528646/abd6f5a5-1f9d-4222-b16d-b187a8022852)
what i need to do?

**Comment by DebianArch64** [comment]
> Your development team has reached the maximum number of registered iPhone devices ![image](https://private-user-images.githubusercontent.com/64528646/298308389-abd6f5a5-1f9d-4222-b16d-b187a8022852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTUyMTYsIm5iZiI6MTcwNTc5NDkxNiwicGF0aCI6Ii82NDUyODY0Ni8yOTgzMDgzODktYWJkNmY1YTUtMWY5ZC00MjIyLWIxNmQtYjE4N2E4MDIyODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIzNTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTA0ZDUyMjIxMTIyM2ZiNGE3YzYxNDY2ZWYyMDg2NmY0ZmRiNGVkZDY1OTQ2OGI0ZWUxNGY0MmE3NmMzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jzeMfcLyS-dnFj51eDw-D7Yc-rVPl3Id6V_llHNw23Y) what i need to do?

Use a different apple account, each apple account can only have two devices registered with it for installs. You can logout by deleting the config folder or running the exe from a different folder

**Comment by Butters07** [comment]
Can I "unregister" a device from my Apple account to allow a new device to be registered?
