### ISSUE TITLE
Time out"?

### ISSUE THREAD

**Issue by JudiexCode** [DebianArch64/DebProvision#23]
![image](https://user-images.githubusercontent.com/106916778/184363346-4fe4f38a-8227-4783-b3bf-31418f211a87.jpeg)

**Comment by DebianArch64** [comment]
> ![image](https://user-images.githubusercontent.com/106916778/184363346-4fe4f38a-8227-4783-b3bf-31418f211a87.jpeg)

The server API seemed to be down - should be fine now
