### ISSUE TITLE
can't install: re-authentication required

### ISSUE THREAD

**Issue by TheCheddarCheese** [DebianArch64/DebProvision#232]
hi, whenever i try to install the app it gives me a 're-authentication required' message, i've tried to log in multiple times using the gui version but it didn't work. i'm on linux, kernel 6.7.4-arch1-1

![image](https://github.com/DebianArch64/DebProvision/assets/124603704/f4f1fd16-3014-4536-8101-ab04deab9730)

**Comment by TheCheddarCheese** [comment]
> run the app with sudo

now i get this:
`WARNING: Native anisette not setup by you. Login issues may occur.`
and it still doesn't let me log in

I know what this means but not necessarily what to do about it

**Comment by Rattlyy** [comment]
It's because armconverter's anisette has been shutdown so it 504's, I tried VM'ing windows scarlet and it also didnt work so I just installed sidestore with said win vm

> > run the app with sudo
> 
> 
> 
> now i get this:
> 
> `WARNING: Native anisette not setup by you. Login issues may occur.`
> 
> and it still doesn't let me log in
> 
> 
> 
> I know what this means but not necessarily what to do about it

**Comment by DebianArch64** [comment]
> It's because armconverter's anisette has been shutdown so it 504's, I tried VM'ing windows scarlet and it also didnt work so I just installed sidestore with said win vm
> 
> > > run the app with sudo
> > 
> > 
> > now i get this:
> > `WARNING: Native anisette not setup by you. Login issues may occur.`
> > and it still doesn't let me log in
> > I know what this means but not necessarily what to do about it

Scarlet uses native anisette on windows and Mac, so it's unrelated to Scarlet that you got the error. Delete the adi files in the iTunes folder apple likely invalidated them
