### ISSUE TITLE
Me again - My computer is next to me and both is connected the same WiFi and I'm plugged into my computer what does "make sure scarletcloud is running mean"?

### ISSUE THREAD

**Issue by JudiexCode** [DebianArch64/DebProvision#24]
![image](https://user-images.githubusercontent.com/106916778/184371121-7e179d03-a84b-45a6-b1fd-da1440f3a17c.png)

**Comment by DebianArch64** [comment]
> ![image](https://user-images.githubusercontent.com/106916778/184371121-7e179d03-a84b-45a6-b1fd-da1440f3a17c.png)

The device must be connected to the computer for Apple to allow installs with a normal apple account - also I posted multiple bug fixes for ScarletCloud today if you can use that instead
