### ISSUE TITLE
Question: will i get banned?

### ISSUE THREAD

**Issue by weiliang011** [DebianArch64/DebProvision#241]
Using scarlet pc and using my personal apple account will result in a ban? and will i get blacklisted? i dont want to get banned and cannot use apple services :(

**Comment by DebianArch64** [comment]
> Using scarlet pc and using my personal apple account will result in a ban? and will i get blacklisted? i dont want to get banned and cannot use apple services :(

Impossible, all this is officially done with apple they allow it
