### ISSUE TITLE
I cant download scarlet cloud on my linux Deb

### ISSUE THREAD

**Issue by Mohamadwwg** [DebianArch64/DebProvision#242]
I wanted to download the cloud on my linux Debian and did this comand in the terminal: 
`./scarletcloudux-linux-arm64` 
but i got this error:
`-bash: ./scarletcloudux-linux-arm64: No such file or directory`

here are the infos about my linux:
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.6.17-01102-gd3cec3c11146
    Architecture: arm64

**Comment by DebianArch64** [comment]
This doesn't have to do with ScarletCloud, you just aren't in the correct directory that the binary is in

If you type 'pwd' it'll tell you your current directory, and to change directories you use 'cd'. You can also just drag the file into terminal and it'll give the full path

**Comment by Mohamadwwg** [comment]
```
Myname@penguin:~$ ls
 libudev.so.0  'scarletcloudux-linux-arm64 '   VSCode
Myname@penguin:~$ ./scarletcloudux-linux-arm64
-bash: ./scarletcloudux-linux-arm64: No such file or directory
```
