### ISSUE TITLE
I need help whit installing scarlet cloud

### ISSUE THREAD

**Issue by Mohamadwwg** [DebianArch64/DebProvision#243]
![Screenshot 2024-04-08 15 47 41](https://github.com/DebianArch64/DebProvision/assets/130875449/89bf0ea0-37a0-4de4-ac68-d001a260c465)

i have a Debian GNU/Linux 12 bookworm

**Comment by DebianArch64** [comment]
This isn't related to ScarletCloud, learn how to use Linux with some guides
