### ISSUE TITLE
Didnt get the AnisettePlugin When downloading scarletcloud on mac

### ISSUE THREAD

**Issue by Thatismagic** [DebianArch64/DebProvision#246]
I can't get the Anisette Plugin to show, but the plugin menu shows for me. I ran the Scarletcloud terminal like in the video.

**Comment by DebianArch64** [comment]
Doesn't exist after Sonoma, don't worry about it

**Comment by Thatismagic** [comment]
I have a monterey mac

**Comment by DebianArch64** [comment]
> I have a monterey mac

The computer method has been getting a rewrite so the current version won't be getting any updates 
https://github.com/DebianArch64/DebProvision/issues/199#issuecomment-1815689871

**Comment by Thatismagic** [comment]
> > I have a monterey mac
> 
> The computer method has been getting a rewrite so the current version won't be getting any updates ![image-50~3](https://private-user-images.githubusercontent.com/63203414/326135541-fc4ecd26-5df5-4159-a5e8-48fcfe431a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzczMDgsIm5iZiI6MTcxNDE3NzAwOCwicGF0aCI6Ii82MzIwMzQxNC8zMjYxMzU1NDEtZmM0ZWNkMjYtNWRmNS00MTU5LWE1ZTgtNDhmY2ZlNDMxYTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAwMTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDA2YTU5YWFhMzFiZjM4MjIyOGM2MzU2NTQ5ZDdlYjAyZjc4ZmUzMzhjZGE1MzQ1MWY5YzY1MTRlZDA0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfPiKgTsFA_jW0wEuWM1jH26FgnmLmnn6kNnK7IWfeQ)
> 
> [#199 (comment)](https://github.com/DebianArch64/DebProvision/issues/199#issuecomment-1815689871)

Ohh

**Comment by Thatismagic** [comment]
> > I have a monterey mac
> 
> The computer method has been getting a rewrite so the current version won't be getting any updates ![image-50~3](https://private-user-images.githubusercontent.com/63203414/326135541-fc4ecd26-5df5-4159-a5e8-48fcfe431a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzczMDgsIm5iZiI6MTcxNDE3NzAwOCwicGF0aCI6Ii82MzIwMzQxNC8zMjYxMzU1NDEtZmM0ZWNkMjYtNWRmNS00MTU5LWE1ZTgtNDhmY2ZlNDMxYTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAwMTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDA2YTU5YWFhMzFiZjM4MjIyOGM2MzU2NTQ5ZDdlYjAyZjc4ZmUzMzhjZGE1MzQ1MWY5YzY1MTRlZDA0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfPiKgTsFA_jW0wEuWM1jH26FgnmLmnn6kNnK7IWfeQ)
> 
> [#199 (comment)](https://github.com/DebianArch64/DebProvision/issues/199#issuecomment-1815689871)

Do you know when it's going to be finished?
