### ISSUE TITLE
I can’t install anything

### ISSUE THREAD

**Issue by DONTTOUCHKAREN** [DebianArch64/DebProvision#249]
It says can’t sideload searching for WI-FI devices when I am connected to my pc and when I’m not it’s the same thing then I use Wirevpn and when it’s starts downloading it gets stuck at 60 an then it says failed creating client handshake

**Comment by DebianArch64** [comment]
> It says can’t sideload searching for WI-FI devices when I am connected to my pc and when I’m not it’s the same thing then I use Wirevpn and when it’s starts downloading it gets stuck at 60 an then it says failed creating client handshake

Don't use the computer if you're using wireguard and you can't use cellular when using wireguard trick because apple blocks usbmuxd wireless installs over cellular
