### ISSUE TITLE
please i need help it say error no response

### ISSUE THREAD

**Issue by Samhenry7** [DebianArch64/DebProvision#25]
![Capture d’écran 2022-08-11 120925](https://user-images.githubusercontent.com/111027104/184434066-37a02e11-6b31-48ae-8a51-a19e3c3e7696.jpg)

**Comment by DebianArch64** [comment]
> ![Capture d’écran 2022-08-11 120925](https://user-images.githubusercontent.com/111027104/184434066-37a02e11-6b31-48ae-8a51-a19e3c3e7696.jpg)

Unrelated to me - has to do with the computer
