### ISSUE TITLE
i cant dowload ipa files and did not see the tweaks app and jealbreak in scarlet app

### ISSUE THREAD

**Issue by Samhenry7** [DebianArch64/DebProvision#26]
![Image](https://user-images.githubusercontent.com/111027104/184550970-01b567b1-2756-4b8d-891d-43e7ff36438f.png)
help me please

**Comment by DebianArch64** [comment]
> ![Image](https://user-images.githubusercontent.com/111027104/184550970-01b567b1-2756-4b8d-891d-43e7ff36438f.png) help me please

Jailbroken repos can be added to the Scarlet app and a sideload button is available in the sideload menu for apps

![20220413_115821~2](https://user-images.githubusercontent.com/63203414/184555365-6c147889-7767-444b-a408-2a098830813f.jpg)
