### ISSUE TITLE
Scarletcloud wont popup

### ISSUE THREAD

**Issue by YeeCrimson** [DebianArch64/DebProvision#264]
```
Waiting for device to be connected...
Connected -> -----------------
Listening on 127.0.0.1:6
Listening on :6969
970
Use the arrow keys to navigate: ↓ ↑ → ←
? Select Action:
  > Connect
    (re)install Scarlet
```

i am stuck in this loop and dont fucking tell me thats CLI use GUI cus i dont know the the fuck either of those are

**Comment by DebianArch64** [comment]
> ```
> Waiting for device to be connected...
> Connected -> -----------------
> Listening on 127.0.0.1:6
> Listening on :6969
> 970
> Use the arrow keys to navigate: ↓ ↑ → ←
> ? Select Action:
>   > Connect
>     (re)install Scarlet
> ```
> 
> i am stuck in this loop and dont fucking tell me thats CLI use GUI cus i dont know the the fuck either of those are

Just search it up, CLI means command-line-interface and GUI means Graphical-User-Interface. GUI is an actual app

**Comment by YeeCrimson** [comment]
alr figured it out
