### ISSUE TITLE
Cant download ipa filed

### ISSUE THREAD

**Issue by Samhenry7** [DebianArch64/DebProvision#27]
![image](https://user-images.githubusercontent.com/111027104/184564704-d5f31752-fa1f-470d-b387-7e40dcc31130.png)![image](https://user-images.githubusercontent.com/111027104/184564710-15d996e9-ea50-49a9-9e3e-dbaca5847368.png)

**Comment by DebianArch64** [comment]
> ![image](https://user-images.githubusercontent.com/111027104/184564704-d5f31752-fa1f-470d-b387-7e40dcc31130.png)![image](https://user-images.githubusercontent.com/111027104/184564710-15d996e9-ea50-49a9-9e3e-dbaca5847368.png)

First off make sure to be connected to the computer and second simply 3D touch this and there is an option to logout of Scarlet - then you can login back into the app

![20220413_115821~2](https://user-images.githubusercontent.com/63203414/184564825-a4c74628-843d-46b5-986d-41c6783cd10c.jpg)
