### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by Samhenry7** [DebianArch64/DebProvision#28]
![image](https://user-images.githubusercontent.com/111027104/184637370-9961805f-7796-4364-ae1a-9e6524519a7c.jpeg)![image](https://user-images.githubusercontent.com/111027104/184637371-46bd1366-14cf-43ea-a827-19427af701f5.jpeg)

**Comment by DebianArch64** [comment]
> ![image](https://user-images.githubusercontent.com/111027104/184637370-9961805f-7796-4364-ae1a-9e6524519a7c.jpeg)![image](https://user-images.githubusercontent.com/111027104/184637371-46bd1366-14cf-43ea-a827-19427af701f5.jpeg)

It means your account or phone has received an authentication code - you need to type it in there
