### ISSUE TITLE
IMac trying to sign into my account?

### ISSUE THREAD

**Issue by DogeMaster201** [DebianArch64/DebProvision#282]
When trying to install the hacked version of Spotify it keeps saying an IMac is trying to sign into my apple account near me but when i accept in gives a code but when I decline it tells me to enter a 2FA code which I don't have.

**Comment by DebianArch64** [comment]
> When trying to install the hacked version of Spotify it keeps saying an IMac is trying to sign into my apple account near me but when i accept in gives a code but when I decline it tells me to enter a 2FA code which I don't have.

It's called anisette, headers that identify a "device" with an apple account. These headers are sent to Apple's xcode API to generate certificates and mobileprovisions for installs, apple expects a "Mac" to be used with xCode.

Here is the line that tricks apple into thinking it's a Mac with a specific version and model number. So in short that "Mac" is your own computer it even says your location, make sure to trust it or else login will not work - this rules apply to any application that makes use of Apple's GSA APIs

https://github.com/DebianArch64/MailPlugin/blob/c9a4cd63713c3d8a97312858e6d48577da409c07/plugin.cpp#L102

**Comment by DogeMaster201** [comment]
Where do I put the line because I'm confused?

**Comment by DebianArch64** [comment]
> Where do I put the line because I'm confused?

You don't put the line anywhere, I just sent it as proof that the "iMac" is your computer. Don't decline the prompt
