### ISSUE TITLE
usbmux connect: dial tcp 127.0.0.1:27015: connectex: No connection could be made because the target machine actively refused it. Press [ENTER] to terminate

### ISSUE THREAD

**Issue by theoeggdog** [DebianArch64/DebProvision#287]
This error in CMD pops up when trying to launch Scarlet.

**Comment by theoeggdog** [comment]
![Screenshot 2024-11-13 182351](https://github.com/user-attachments/assets/5755b200-5129-43fe-b8a9-f3e4ef65a776)

**Comment by DebianArch64** [comment]
> This error in CMD pops up when trying to launch Scarlet.

This is a duplicate issue, 27015 is the port Apple's usbmuxd service runs on, you don't have iTunes exe installed
