### ISSUE TITLE
it says Waiting for device to be connected... i,ve 

### ISSUE THREAD

**Issue by Rg4r** [DebianArch64/DebProvision#3]
i,ve  waited a hour and am connected to via USB i have download iTunes

This issue in Windows 64 bit and 36 bit 

> > i,ve  waited a hour and am connected to via USB i have download iTunes
> > This issue in Windows 64 bit and 36 bit
> 
> Just means your computer doesn't detect your device it's not an issue with ScarletCloud, but instead how you set it up
> 
> Make sure to restart your computer after installing iTunes and that iTunes was installed from https://support.apple.com/en-us/HT210384 instead of the one from the Microsoft store

Alright iam gonna Check it if it works

**Comment by Rg4r** [comment]
> > i,ve  waited a hour and am connected to via USB i have download iTunes
> > This issue in Windows 64 bit and 36 bit
> 
> Just means your computer doesn't detect your device it's not an issue with ScarletCloud, but instead how you set it up
> 
> Make sure to restart your computer after installing iTunes and that iTunes was installed from https://support.apple.com/en-us/HT210384 instead of the one from the Microsoft store



Ma Brother Still the issue

**Comment by DebianArch64** [comment]
> > > i,ve  waited a hour and am connected to via USB i have download iTunes
> > > This issue in Windows 64 bit and 36 bit
> > 
> > Just means your computer doesn't detect your device it's not an issue with ScarletCloud, but instead how you set it up
> > 
> > Make sure to restart your computer after installing iTunes and that iTunes was installed from https://support.apple.com/en-us/HT210384 instead of the one from the Microsoft store
> 
> 
> 
> Ma Brother Still the issue

Once again all based on the USB drivers on the device I hope you can figure out what's wrong with the computer, but stuff like that is out of my control

**Comment by Rg4r** [comment]
> > > > i,ve  waited a hour and am connected to via USB i have download iTunes
> > > > This issue in Windows 64 bit and 36 bit
> > > 
> > > 
> > > Just means your computer doesn't detect your device it's not an issue with ScarletCloud, but instead how you set it up
> > > Make sure to restart your computer after installing iTunes and that iTunes was installed from https://support.apple.com/en-us/HT210384 instead of the one from the Microsoft store
> > 
> > 
> > Ma Brother Still the issue
> 
> Once again all based on the USB drivers on the device I hope you can figure out what's wrong with the computer, but stuff like that is out of my control



i updated everything and my usb works fine Can you Check it again

**Comment by DebianArch64** [comment]
> > > > > i,ve  waited a hour and am connected to via USB i have download iTunes
> > > > > This issue in Windows 64 bit and 36 bit
> > > > 
> > > > 
> > > > Just means your computer doesn't detect your device it's not an issue with ScarletCloud, but instead how you set it up
> > > > Make sure to restart your computer after installing iTunes and that iTunes was installed from https://support.apple.com/en-us/HT210384 instead of the one from the Microsoft store
> > > 
> > > 
> > > Ma Brother Still the issue
> > 
> > 
> > Once again all based on the USB drivers on the device I hope you can figure out what's wrong with the computer, but stuff like that is out of my control
> 
> i updated everything and my usb works fine Can you Check it again

Nothing to check for ScarletCloud uses an official framework for USB connections and it communicates with the official Unix socket running on the device the only possible way it can fail is if the device doesn't have the drivers. Try connecting your phone into different ports or with a different cable, but there is nothing on my end to fix
