### ISSUE TITLE
Support for macOS Mojave

### ISSUE THREAD

**Issue by tuancuongitit** [DebianArch64/DebProvision#31]
Hi,

Could you please add support for macOS Mojave 10.14.6.

Thanks a lot!

**Comment by DebianArch64** [comment]
> Hi,
> 
> Could you please add support for macOS Mojave 10.14.6.
> 
> Thanks a lot!

The binary should support it - try running it manually instead of from .app file /Applications/ScarletCloud.app/Contents/MacOS/scarletcloud
