### ISSUE TITLE
Your team has no devices from which to generate a provisioning profile.

### ISSUE THREAD

**Issue by verbes4** [DebianArch64/DebProvision#32]
Getting this error: 
`Your team has no devices from which to generate a provisioning profile. Connect a device to use or manually add device IDs in Certificates, Identifiers & Profiles. https://developer.apple.com/account/`
I cant find a Certificates, Identifiers & Profiles section on the developer site so idk what to do.

**Comment by DebianArch64** [comment]
> Getting this error: `Your team has no devices from which to generate a provisioning profile. Connect a device to use or manually add device IDs in Certificates, Identifiers & Profiles. https://developer.apple.com/account/` I cant find a Certificates, Identifiers & Profiles section on the developer site so idk what to do.

ScarletCloud automatically adds your device to your account if it's not already registered - from what I've heard apple now takes a while for the changes to show

If you try it now it should be fine

**Comment by vip93** [comment]
hello im not found Scarletcloud in profile github ?

**Comment by DebianArch64** [comment]
> hello im not found Scarletcloud in profile github ? For Mac

Click the releases button
