### ISSUE TITLE
pkcs 12: error reading P12 data: syntax error: squence truncated

### ISSUE THREAD

**Issue by mAmged** [DebianArch64/DebProvision#33]
I installed Scarlet one time and it was working 100% fine. then I deleted it and trying to reinstall again but I get this error.
![image](https://user-images.githubusercontent.com/1144321/187488484-c34b425c-187b-4cb1-9a8e-d18dc208b84a.png)

**Comment by DebianArch64** [comment]
> I installed Scarlet one time and it was working 100% fine. then I deleted it and trying to reinstall again but I get this error. ![image](https://user-images.githubusercontent.com/1144321/187488484-c34b425c-187b-4cb1-9a8e-d18dc208b84a.png)

Delete the ScarletCloud app from the applications folder and reinstall it
