### ISSUE TITLE
Mail has disabled the following plug-ins:  AnisettePlugin.mailbundle

### ISSUE THREAD

**Issue by lepantella** [DebianArch64/DebProvision#37]
Whenever I enable the AnisettePlugin inside Mail Preferences, I get this error

![image](https://user-images.githubusercontent.com/2305733/189113029-7dffd900-f966-4ee5-8054-d123e80f1a25.png)

**Comment by DebianArch64** [comment]
> Whenever I enable the AnisettePlugin inside Mail Preferences, I get this error
> 
> ![image](https://user-images.githubusercontent.com/2305733/189113029-7dffd900-f966-4ee5-8054-d123e80f1a25.png)

This can't exactly be fixed - Apple designed MailPlugins so that for each Mac update it needs to explicitly have keys for that mail version and that MacOS version and the UUID. Best option is to go with Linux or Windows for ScarletCloud

**Comment by lepantella** [comment]
Which verison of mail do you have, so I can at least downgrade somehow?

**Comment by DebianArch64** [comment]
> Which verison of mail do you have, so I can at least downgrade somehow?

MacOS system updates are the ones that downgrade/upgrade the mail app 

You can remove the MailPlugin so that alternatively Scarlet uses anisette from my server instead of the system: sudo rm -r "/Library/Mail/Bundles/AnisettePlugin.mailbundle"

**Comment by lepantella** [comment]
I still don't understand, I removed the mail plugin, made sure that ScarletCloud is up and running, that my phone is jacked in and I still get "Make sure ScarletCloud is running" when I try to download uYou for example.

**Comment by MohammadAbdulRafe** [comment]
Have you found any way to solve this problem?

**Comment by Muhammed8666** [comment]
AnisettePlugin.mailbundle
