### ISSUE TITLE
ScarletCloud failed to verify code signature

### ISSUE THREAD

**Issue by Zany-Zachary1** [DebianArch64/DebProvision#47]
I reinstalled iTunes and iCloud again after updating to iOS 16, and upon trying to sideload scarlet using scarletcloud, I get this behemoth of an error:
```
- Please wait as Scarlet sideloads.
mkdir C:\Users\zacha\Downloads\config: Cannot create a file when that file already exists.
receive packet: ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.d2CFko/extracted/Payload/Scarlet.app : 0xe8008015 (A valid provisioning profile for this executable was not found.))
```
PC OS: Windows 11 Pro 21H2
iOS: iOS 16.0 (20A362)

Sorry for another bug my man

**Comment by DebianArch64** [comment]
> I reinstalled iTunes and iCloud again after updating to iOS 16, and upon trying to sideload scarlet using scarletcloud, I get this behemoth of an error:
> 
> ```
> - Please wait as Scarlet sideloads.
> mkdir C:\Users\zacha\Downloads\config: Cannot create a file when that file already exists.
> receive packet: ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.d2CFko/extracted/Payload/Scarlet.app : 0xe8008015 (A valid provisioning profile for this executable was not found.))
> ```
> 
> PC OS: Windows 11 Pro 21H2 iOS: iOS 16.0 (20A362)
> 
> Sorry for another bug my man

Hmm that's odd because ScarletCloud grabs the provisioning profile from apple each time it doesn't save it. 

I guess you could try deleting the config folder and clicking install Scarlet again - If you need any more help make sure to DM me on Twitter @GetScarlet
