### ISSUE TITLE
how do i even use/install this?

### ISSUE THREAD

**Issue by lewiwiii** [DebianArch64/DebProvision#48]
need some help on this please :)

**Comment by DebianArch64** [comment]
> need some help on this please :)

![Screenshot_20221002-135209](https://user-images.githubusercontent.com/63203414/195936856-e96e578b-429e-4969-a451-2401d9edd2c8.png)
First step is to make sure the requirements for your computer are installed

Then you can download ScarletCloud from the releases page
![Screenshot_20221002-135217](https://user-images.githubusercontent.com/63203414/195937127-f16536d1-0b81-4950-8b33-4d08b55fa504.png)

After that run ScarletCloud, select your device, and click install
![167322320-9c29da0a-7624-4e20-bc04-9b5849095a17](https://user-images.githubusercontent.com/63203414/195937250-428a13f9-a621-4818-a484-809fc4e0c461.png)

If you need any more help make sure DM me on Twitter @GetScarlet and I'll get to you soon ;)
