### ISSUE TITLE
mail plugin incompatible with macOS 16.0

### ISSUE THREAD

**Issue by geomoney001** [DebianArch64/DebProvision#49]
I did everything just to find that the latest macOS update and the mail plugin are not compatible does anyone have a way to resolve this issue?

**Comment by bthedorff** [comment]
Just came here to post about this.  Running `sudo /Applications/ScarletCloud.app/Contents/MacOS/scarletcloud` doesn't fix the errors even after a clean install aka running sudo first run. I tried both GUI and Beta running both .dmg and the macho file.

MacOS Monterey 12.5.1
Mail Version 16.0 (3696.120.41.1.1)

**Comment by Zany-Zachary1** [comment]
Check #37 for an explanation.

Basically it can't be fixed, as it's on Apple's side.  Best to use Linux or Windows :)

**Comment by bthedorff** [comment]
> Check #37 for an explanation.
> 
> Basically it can't be fixed, as it's on Apple's side. Best to use Linux or Windows :)

Yeah I ended up seeing after a little more digging. It should really be removed if it can't be fixed. Also Sideloady and Alt-Store have a similar plug-in that works but idk what the difference between this one and those are

**Comment by DebianArch64** [comment]
> > Check #37 for an explanation.
> > Basically it can't be fixed, as it's on Apple's side. Best to use Linux or Windows :)
> 
> Yeah I ended up seeing after a little more digging. It should really be removed if it can't be fixed. Also Sideloady and Alt-Store have a similar plug-in that works but idk what the difference between this one and those are

Mail Plugins require a lot of manual updating for every release - ScarletCloud does it's best by auto-patching it, but it's not enough. I'll go ahead and make a proper fix today

I'm also working on app refresh, so the two should be released at the same time

**Comment by bthedorff** [comment]
> > > Check #37 for an explanation.
> > > Basically it can't be fixed, as it's on Apple's side. Best to use Linux or Windows :)
> > 
> > 
> > Yeah I ended up seeing after a little more digging. It should really be removed if it can't be fixed. Also Sideloady and Alt-Store have a similar plug-in that works but idk what the difference between this one and those are
> 
> Mail Plugins require a lot of manual updating for every release - ScarletCloud does it's best by auto-patching it, but it's not enough. I'll go ahead and make a proper fix today
> 
> I'm also working on app refresh, so the two should be released at the same time

So it is possible to fix? Is it possible to program it to check for Sideloady's plug-in or AltStore's plug-in and use those if available? Might save some work in your end.

**Comment by DebianArch64** [comment]
> > > > Check #37 for an explanation.
> > > > Basically it can't be fixed, as it's on Apple's side. Best to use Linux or Windows :)
> > > 
> > > 
> > > Yeah I ended up seeing after a little more digging. It should really be removed if it can't be fixed. Also Sideloady and Alt-Store have a similar plug-in that works but idk what the difference between this one and those are
> > 
> > 
> > Mail Plugins require a lot of manual updating for every release - ScarletCloud does it's best by auto-patching it, but it's not enough. I'll go ahead and make a proper fix today
> > I'm also working on app refresh, so the two should be released at the same time
> 
> So it is possible to fix? Is it possible to program it to check for Sideloady's plug-in or AltStore's plug-in and use those if available? Might save some work in your end.
> 
> Edit: Pretty sure sideloady does this is you already have AltStore installed

Yeah definitely possible, but honestly ScarletCloud's plugin is already built fine - pretty sure it's the first plugin for an altstore alternative to be made in pure C++ and it also auto patches which will become extra useful once I add the fix

**Comment by DebianArch64** [comment]
Quick update. I didn't forget to work on this I started today since my computer broke down and managed to push an app refresh update to the Scarlet app.

MailPlugin stuff has most of the code finished, but I'm mainly been trying to update my Ryzentosh to actually confirm if the fix fully works

Anyways thanks for being patient with me and updates and changes will be tweeted on @DebianArch and @GetScarlet twitter

**Comment by DebianArch64** [comment]
![PXL_20221110_140734635](https://user-images.githubusercontent.com/63203414/201114330-cd89debd-1a0b-4f64-8562-8b83bad50739.jpg)

I had to get a real Mac because I couldn't update my Ryzentosh. I'm adding a couple things to make Mac support great.

- A backup anisette server when native anisette fails and it couldn't contact Scarlets own anisette server
- I noticed that Apple added new security because anything fakesigned also throws that "unsupported" message

To fix the MailPlugin I'll temporarily ship ScarletCloud with AltStores MailPlugin - it'll fetch it and automatically update it

**Comment by tkit0428** [comment]
> ![PXL_20221110_140734635](https://user-images.githubusercontent.com/63203414/201114330-cd89debd-1a0b-4f64-8562-8b83bad50739.jpg)
> 
> I had to get a real Mac because I couldn't update my Ryzentosh. I'm adding a couple things to make Mac support great.
> 
> * A backup anisette server when native anisette fails and it couldn't contact Scarlets own anisette server
> * I noticed that Apple added new security because anything fakesigned also throws that "unsupported" message
> 
> To fix the MailPlugin I'll temporarily ship ScarletCloud with AltStores MailPlugin - it'll fetch it and automatically update it.
> 
> So far I did manage to make it works 🎉

Looks great can’t wait to try it later

thx for all the work you did this shit is amazing

**Comment by DebianArch64** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63203414/201680340-f91cba10-abfb-47ca-9d8b-c032547b637d.png">

I've been working on a couple things for the next update of ScarletCloud. I was able to get back the anisette data from the AltStore plugin and the backup anisette server works great when not using a MailPlugin at all.

Really only thing left is to parse the information in that screenshot. I have also heavily improved device connections and even recreated what apples does for Wifi-Sync for 100% success rate wireless connections

**Comment by Zany-Zachary1** [comment]
> Really only thing left is to parse the information in that screenshot. I have also heavily improved device connections and even recreated what apples does for Wifi-Sync for 100% success rate wireless connections - without UPNP.

So... I don't need to plug the phone into my computer to sideload??? 👌can't wait

**Comment by DebianArch64** [comment]
> > Really only thing left is to parse the information in that screenshot. I have also heavily improved device connections and even recreated what apples does for Wifi-Sync for 100% success rate wireless connections - without UPNP.
> 
> So... I don't need to plug the phone into my computer to sideload??? 👌can't wait

Yes - the wireless feature currently works by having ANY phone or computer on the same network run a simple program and then like magic the phone can sideload apps

One day it'll be possible to not have any other device for sideloading by using some tricks with the router

**Comment by DebianArch64** [comment]
This issue will now be closed as this issue was fixed with the latest commit. Make sure to update ScarletCloud from the GUI releases page and tell me if you run into any issues.
