### ISSUE TITLE
How to fix this one?

### ISSUE THREAD

**Issue by sazzeh** [DebianArch64/DebProvision#50]
![A24BB7D7-5C67-455A-BF94-93124993BADE](https://user-images.githubusercontent.com/115914298/196019870-4fe3fbee-f004-4bca-a8fd-bb843c869735.png)

**Comment by DebianArch64** [comment]
> ![A24BB7D7-5C67-455A-BF94-93124993BADE](https://user-images.githubusercontent.com/115914298/196019870-4fe3fbee-f004-4bca-a8fd-bb843c869735.png)

Check the computer for the real error message (the black window) - what does it say

**Comment by sazzeh** [comment]
![Uploading 585DABFA-E247-4B74-8783-67C86205EFA6.png…]()

**Comment by sazzeh** [comment]
![image](https://user-images.githubusercontent.com/115914298/196085448-f9559024-9a2e-4c81-863b-99e3f2f6ee1d.jpg)

**Comment by sazzeh** [comment]
![07B416A2-9692-4837-8398-2D3E30F873F5](https://user-images.githubusercontent.com/115914298/196085555-728c121f-2f1b-4953-b4a8-b82b0e0e5d3d.png)
![F9A68454-7C37-44B9-8ADD-2958B58EA279](https://user-images.githubusercontent.com/115914298/196085566-15d1755a-7b45-4c1a-81a2-36ec3b2accac.png)

**Comment by DebianArch64** [comment]
> ![07B416A2-9692-4837-8398-2D3E30F873F5](https://user-images.githubusercontent.com/115914298/196085555-728c121f-2f1b-4953-b4a8-b82b0e0e5d3d.png) ![F9A68454-7C37-44B9-8ADD-2958B58EA279](https://user-images.githubusercontent.com/115914298/196085566-15d1755a-7b45-4c1a-81a2-36ec3b2accac.png)

![20220930_063230](https://user-images.githubusercontent.com/63203414/196176366-af6b9af6-9548-4c9d-8d91-42ef8350f637.jpg)
3D touch this button so you can logout of your account and enter the information correctly

Your device needs to be plugged into your computer with ScarletCloud opened on the computer
