### ISSUE TITLE
Mail plugin Mail14

### ISSUE THREAD

**Issue by tkit0428** [DebianArch64/DebProvision#53]
I know there are many people already posted this but they're all mail16

Mail14 also have this problem?
![Screen Shot 2022-11-09 at 7 43 17 PM](https://user-images.githubusercontent.com/66514683/200972681-aab393f3-f087-48e0-891c-87d1ac3f5d72.jpg)

**Comment by DebianArch64** [comment]
> I know there are many people already posted this but they're all mail16
> 
> Mail14 also have this problem? ![Screen Shot 2022-11-09 at 7 43 17 PM](https://user-images.githubusercontent.com/66514683/200972681-aab393f3-f087-48e0-891c-87d1ac3f5d72.jpg)

Yeah it's all related to each other. A major update is being worked on that introduces better connectivity and better MailPlugin support.

The issue with MailPlugins is for every update new keys need to be added to the MailPlugins Info.plist and although ScarletCloud does this automatically it looks like it's not enough anymore

You'll find update posts on @DebianArch and @GetScarlet Twitter pages - I'll also make sure to notify you. For the meantime I recommend using the windows version instead
