### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tkit0428** [DebianArch64/DebProvision#54]
is .deb supported

**Comment by DebianArch64** [comment]
> is .deb supported

Yes you can add jailbroken repos without a jailbreak to install apps or tweak apps.

You can also import .deb and .dylib files from the files app

**Comment by tkit0428** [comment]
For some reason I got bunch of unknown deb category error

**Comment by DebianArch64** [comment]
> For some reason I got bunch of unknown deb category error

Don't click the install button more than once. Let it finish

I don't see how it could fail unless the deb itself is invalid - I checked the official documentation of deb files and there are only four used types which Scarlet supports already.

If you can send the deb or the repo you got this error on I'll get back to you with more info

<img width="718" alt="image" src="https://user-images.githubusercontent.com/63203414/201257116-7c55204d-df0d-4082-83ee-73d84605be56.png">

**Comment by tkit0428** [comment]
Basically all pactrix apps
