### ISSUE TITLE
Unable to install successfully from the computer

### ISSUE THREAD

**Issue by dfvips** [DebianArch64/DebProvision#57]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/21048630/202616207-cfb2fd7a-b75b-4889-a066-89fcee3f43d1.png">
The method of installing through the computer cannot be successful.I tried many times, but I was always prompted to log in again, even my AppleID was locked.

**Comment by dfvips** [comment]
Logs:
2022/11/18 12:30:58 Fyne error:  GLFW poll event error: InvalidValue: Invalid scancode
2022/11/18 12:30:58   At: /Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:257
2022/11/18 12:30:59 Fyne error:  GLFW poll event error: InvalidValue: Invalid scancode
2022/11/18 12:30:59   At: /Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:257
2022/11/18 12:31:08 Fyne error:  GLFW poll event error: InvalidValue: Invalid scancode
2022/11/18 12:31:08   At: /Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/loop.go:257
Anisette fetch timed out. Make sure AnisettePlugin is enabled and Mail app is open.
2022/11/18 12:32:15 [PLS2R] Err: Post "https://gsa.apple.com/grandslam/GsService2": EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x100978284]

goroutine 29 [running]:
usescarlet.com/debserver/gsa.GSALogin({0x1400002ce90, 0xd}, {0x140000268b8, 0x13}, {0x1009b9655, 0x15})
	/Users/debianarch/Documents/ScarletGSA/gsamain.go:98 +0x204
usescarlet.com/debserver/gsa.ProvisionerLogin({0x1400002ce90?, 0x100557584?}, {0x140000268b8?, 0x30000007d?}, {0x1009b9655, 0x15})
	/Users/debianarch/Documents/ScarletGSA/debprovision.go:155 +0x2c
main.main.func5.1()
	/Users/debianarch/Documents/ScarletServer/main.go:113 +0xd0
fyne.io/fyne/v2/widget.(*Button).Tapped(0x14001286320, 0x140003802c4)
	/Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/widget/button.go:194 +0x4c
fyne.io/fyne/v2/internal/driver/glfw.(*window).mouseClickedHandleTapDoubleTap.func1()
	/Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:909 +0x2c
fyne.io/fyne/v2/internal/driver/common.(*Window).RunEventQueue(0x14000380200)
	/Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/common/window.go:58 +0x4c
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	/Users/debianarch/go/pkg/mod/fyne.io/fyne/v2@v2.1.4/internal/driver/glfw/window.go:1413 +0x158

**Comment by dfvips** [comment]
My system is Mac OS 13.0,can you give me some help?

**Comment by DebianArch64** [comment]
> My system is MacOS 13.0,can you give me some help?

I'll check it out when I get back home

**Comment by dfvips** [comment]
Okey doke. Thanks.

**Comment by DebianArch64** [comment]
> ScarletGSA

Based on my observation the error happens around where ScarletCloud checks if M2 key is valid - if it's not it means there was an error most likely related to anisette.

Since 'M2' was null it caused the app to crash. 

Fix: Make sure ScarletCloud is generating anisette natively by enabling the MailPlugin inside Mail app settings.

Also to unlock the account just login to your account from the browser

**Comment by dfvips** [comment]
Yeah, my device is an M2 chip, but where is the MailPlugin in the Mail app settings? Can you provide an screenshot?

**Comment by DebianArch64** [comment]
> Yeah, my device is the M2 chip, but where is the MailPlugin in the Mail app settings? The plugin directory in my Mail app settings is blank. Can you provide an screenshot?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63203414/202820071-e7d9b08c-ad9d-4d81-9c3b-840e44f367bc.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63203414/202820130-f6769a72-2470-4dc0-b99a-cd21ee6ae73c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63203414/202820154-47ee9222-5ada-4c33-92ae-7bbfdacb575b.png">

**Comment by dfvips** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/21048630/202821260-3a2b66e9-7312-45c0-8f97-8a83a3bada3a.png">
I cannot find the "Manage Plug-Ins" button.

**Comment by dfvips** [comment]
After I installed the SmallCubed MailSuite, I found this button, then I have successfully installed. Thanks.

**Comment by DebianArch64** [comment]
> After I installed the SmallCubed MailSuite, I found this button, then I have successfully installed. Thanks.

Next ScarletCloud update for Mac fixes the issue with plugin option not showing 

Enjoy
