### ISSUE TITLE
Unable to sign you into your apple id

### ISSUE THREAD

**Issue by FinderProcess** [DebianArch64/DebProvision#60]
I get this message in the app after sideloading the app i login and i follow the exact steps in the tutorial.

**Comment by DebianArch64** [comment]
> I get this message in the app after sideloading the app i login and i follow the exact steps in the tutorial.

Which "unable to sign into your apple id" - if it's the -36607 one choose an anisette server from the list of options it prompts you with

**Comment by FinderProcess** [comment]
![IMG_0376](https://user-images.githubusercontent.com/97183873/204144082-29cf163c-af8d-4fa7-8273-c688eccf3ac6.png)

**Comment by FinderProcess** [comment]
I have tried deleting and fully redo the whole process twice now nothing seems to work

**Comment by DebianArch64** [comment]
> I have tried deleting and fully redo the whole process twice now nothing seems to work

Please don't use the YouTuber version of ScarletCloud

Get the version made for users here - there is a warning about using the YouTuber version
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63203414/204144336-db46aaa4-dc69-441f-b043-abce9c7478c8.png">

**Comment by FinderProcess** [comment]
> 

Okay thx for the help i got it to work now.
