### ISSUE TITLE
Failed to create installation proxy

### ISSUE THREAD

**Issue by Felting** [DebianArch64/DebProvision#63]
While trying to refresh Scarlet in the app with vpn on, it gets to 50% and then says "Failed Install Failed to create installation proxy."

**Comment by DebianArch64** [comment]
> While trying to refresh Scarlet in the app with vpn on, it gets to 50% and then says "Failed Install Failed to create installation proxy."

Make sure you are on Wi-Fi - also try turning on and off wireguard then restarting scarlet app

**Comment by Felting** [comment]
Now it says Failed Install This device has reached the maximum n...

**Comment by DebianArch64** [comment]
> Now it says Failed Install This device has reached the maximum n...

You can't have more than three apps installed at a time
