### ISSUE TITLE
Resigned Scarlet Requires Wired Computer Connection

### ISSUE THREAD

**Issue by gharshit606** [DebianArch64/DebProvision#64]
I installed scarlet 2 days ago so yesterday i decided to check whether the refresh process actually works or not without computer… So I refreshed the scarlet app and it perfectly created another scarlet application on my homescreen… When i opened that and tried to install an app using that new scarlet then it gives me an error “wired computer connection is required” , and to fix that we again required our PC to transfer assets to the refreshed scarlet app too which makes it the same software just like Altstore or if its a bug then please let me know when will you going to release the next update to fix this bug? Is there any other version of scarlet available which is working fine with the refresh process?

**Comment by DebianArch64** [comment]
> I installed scarlet 2 days ago so yesterday i decided to check whether the refresh process actually works or not without computer… So I refreshed the scarlet app and it perfectly created another scarlet application on my homescreen… When i opened that and tried to install an app using that new scarlet then it gives me an error “wired computer connection is required” , and to fix that we again required our PC to transfer assets to the refreshed scarlet app too which makes it the same software just like Altstore or if its a bug then please let me know when will you going to release the next update to fix this bug? Is there any other version of scarlet available which is working fine with the refresh process?

Update Scarlet with ScarletCloud it fixes the app duplication and refresh bugs
