### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by iKn0wThingz** [DebianArch64/DebProvision#67]
app crashes when"Scarlet ios app" and "scarletcloudux-windows-386 on windows" is open.
ios app says Cant sideload wired connection
ipad air 8 16.2 beta 4

**Comment by DebianArch64** [comment]
> app crashes when"Scarlet ios app" and "scarletcloudux-windows-386 on windows" is open. ios app says Cant sideload wired connection ipad air 8 16.2 beta 4

"Wired communication with computer needed first" - means connect your phone to your computer before using it wirelessly
