### ISSUE TITLE
Getting this error on arch linux

### ISSUE THREAD

**Issue by Hazem42** [DebianArch64/DebProvision#69]
![Screenshot_20221207_143417](https://user-images.githubusercontent.com/89294365/206180663-63a1287a-b720-4953-80bf-7c981b3e97db.png)

**Comment by DebianArch64** [comment]
> ![Screenshot_20221207_143417](https://user-images.githubusercontent.com/89294365/206180663-63a1287a-b720-4953-80bf-7c981b3e97db.png)

Nothing that can be fixed - when the device can't generate anisette natively it goes to an anisette server. There are two backup ones and even if it did fall back onto one apple automatically makes them unusable
