### ISSUE TITLE
Apple ID-Login (not gui ver)

### ISSUE THREAD

**Issue by KevinAlavik** [DebianArch64/DebProvision#7]
When i log in with my apple id i get this error:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/95900603/169647058-359cfffd-09ee-4feb-965f-c6b7a09cf15e.png">

**Comment by DebianArch64** [comment]
This is caused when there are no teams registered with your account - it's an odd abnormality you experienced. Might be that you didn't accept the Apple terms from https://developer.apple.com/account/ - tell me if that fixes it for you on that account you used
