### ISSUE TITLE
STILL cannot sideload with windows

### ISSUE THREAD

**Issue by zek-c** [DebianArch64/DebProvision#72]
403 error on resources.usescarlet.com/api/sign?beta=30
![49C6A88C-DA31-4E18-A817-B86F1473C903](https://user-images.githubusercontent.com/105883248/207200286-e925b397-805a-4927-ac63-024202d284d3.jpeg)

**Comment by nbycoder** [comment]
> 403 error on resources.usescarlet.com/api/sign?beta=30 ![49C6A88C-DA31-4E18-A817-B86F1473C903](https://user-images.githubusercontent.com/105883248/207200286-e925b397-805a-4927-ac63-024202d284d3.jpeg)

same here on linux

**Comment by DebianArch64** [comment]
> > 403 error on resources.usescarlet.com/api/sign?beta=30 ![49C6A88C-DA31-4E18-A817-B86F1473C903](https://user-images.githubusercontent.com/105883248/207200286-e925b397-805a-4927-ac63-024202d284d3.jpeg)
> 
> same here on linux

As mentioned it's a server error. I had to deal with tornados and exams today so I'm a bit busy ATM

I changed how it proxies to the API and it should now work consistently fine

**Comment by DebianArch64** [comment]
Closing this because servers have been fine for a day - switching to a dedicated server hopefully over the Christmas break
