### ISSUE TITLE
Add Support for AltStore Repos

### ISSUE THREAD

**Issue by yodaluca23** [DebianArch64/DebProvision#74]
Add support for AltStore repositories to be added to the Scarlet app.

Alt store repos have been around for a long time therefore There's a significant amount of really good ones and it would make it super convenient and better if Scarlet could support them for automatic updates and viewing this would also make Scarlett be able to support like four different types of repos which would be super cool.

**Comment by AlexSpaces** [comment]
He won't do that because he didn't develop the format and it's clunky

**Comment by DebianArch64** [comment]
I didn't create AltStore, so there isn't a need for me to support it - 

I recommend taking a look at this repo or using IPA library websites
https://ipa.cypwn.xyz
