### ISSUE TITLE
IT HAS BEEN FIXED NOW YOU CAN CLOSE THIS

### ISSUE THREAD

**Issue by KeiKei-2** [DebianArch64/DebProvision#75]
![Screenshot 2022-12-14 192350](https://user-images.githubusercontent.com/95989028/207750660-068cdf83-d293-40d3-9d67-bed53839cba6.png)

**Comment by KeiKei-2** [comment]
WHAT DO I DO WHAT DID I DO WRONG

**Comment by DebianArch64** [comment]
> WHAT DO I DO WHAT DID I DO WRONG

How how did you fix it - for future reference ?

**Comment by KeiKei-2** [comment]
> > WHAT DO I DO WHAT DID I DO WRONG
> 
> How how did you fix it - for future reference ?

I moved the file from downloads into a different folder
