### ISSUE TITLE
How to install linux file

### ISSUE THREAD

**Issue by gavin02031** [DebianArch64/DebProvision#76]
How can I install the linux file since it does not have a .deb after the file name?

**Comment by Zany-Zachary1** [comment]
All you have to do is run it!  But before you run it, make sure to make it executable.  You can do this alot of ways, but I'll share two.
In file manager of your choice, right-click on it, go to properties, and check "Allow Executing Files as Programs", then double click it.
In the terminal, cd to the parent directory, and type this command:
```
chmod +x the-scarlet-file
```
then all you have to do is:
```
./the-scarlet-file
```
