### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by belyy1337** [DebianArch64/DebProvision#77]
yoo i got banned when used gui version💀💀💀

**Comment by DebianArch64** [comment]
> yoo i got banned when used gui version💀💀💀

? You can't be banned. There is a warning on this site that says to setup native anisette or else you risk apple throwing security alerts.

If you're on windows install iCloud and iTunes (if it says permission error in the black window run as admin). If it's Mac enable the MailPlugin

**Comment by belyy1337** [comment]
ok now its fine, but now it says i need wired connection with pc, when i already connected
