### ISSUE TITLE
Unable to verify apps

### ISSUE THREAD

**Issue by MagicGideonL** [DebianArch64/DebProvision#79]
So I'm having an issue with scarlet today where I refreshed the application yesterday and it completed with no problem, this morning I woke up to it, just crashing out of nowhere. So I checked the settings and it said unable to verify applications. Verify this on a wifi connection. So I try to verify the application, but it wouldn't go through. Is this normal for scarlet???

**Comment by Whitewolfbtd** [comment]
This is also a problem with me since I spent all day redownloading and not working I even updated to the latest version but no work please help

**Comment by DebianArch64** [comment]
Make sure you both aren't using other computer methods as they will revoke ALL active certificates
