### ISSUE TITLE
"Only one usage of each socket address" error

### ISSUE THREAD

**Issue by DetachHead** [DebianArch64/DebProvision#8]
![image](https://user-images.githubusercontent.com/57028336/169692999-0e4b2750-b579-40c4-8507-e2d2fd6ed676.png)

i noticed that this `AppleMobileDeviceProcess` was also using that port:
```
> Get-Process -Id (Get-NetTCPConnection -LocalPort 27015).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    312      28     4332      15696      45.97  16212   2 AppleMobileDeviceProcess
```

so i tried killing it, but now i get this error:

![image](https://user-images.githubusercontent.com/57028336/169693141-97f05b8a-5cd5-422a-a96a-dd11ca3907e8.png)

**Comment by DebianArch64** [comment]
That's the Windows iTunes process - 27015 is the TCP socket for USB communications. I'll see about making a permanent fix, but for now restart your computer or something - shouldn't be an error that occurs multiple times at once

**Comment by DebianArch64** [comment]
For future reference - this issue *should* be entirely in the past now including other visual and connection bugs - if anyone can confirm this I'll close this issue

**Comment by DebianArch64** [comment]
Great news this issue no longer exists ! I'm getting feedback that it now works on the first try without any sort of connection issues - can't wait to implement native anisette on Linux next 🕺
