### ISSUE TITLE
Some apps are not sideloading

### ISSUE THREAD

**Issue by fqhy** [DebianArch64/DebProvision#80]
Apps like uYou, uYou+ are not side loading even after using different iPAs. ScarletCloud shows that app is sided loaded successfully, but on app it is stuck on 99% of side loading, and if leave the app and go on home screen there’s no app. Original YouTube removed.

**Comment by fqhy** [comment]
Using Win10, A11, 15.6
Some apps like iPoGo not installing as well.

**Comment by fqhy** [comment]
Apparently, after a lot of installations Scarlet got logged out of Apple ID for some reason, and while installing, app got on home screen, even though it is not showing up in the app. uYou+ works fine but as already stated, doesn’t show up in Scarlet. Also, now, I can’t install any app, and I get an error trying to install (refer to screenshot)
![CBE04EC9-5B0E-46E9-9CD8-3CB51CC2BF57](https://user-images.githubusercontent.com/49283302/209318451-c8878149-c423-4bd5-9e17-7c321692c8ac.jpeg)

**Comment by DebianArch64** [comment]
> Apps like uYou, uYou+ are not side loading even after using different iPAs. ScarletCloud shows that app is sided loaded successfully, but on app it is stuck on 99% of side loading, and if leave the app and go on home screen there’s no app. Original YouTube removed.

If the Sideload menu doesn't disappear then it's not done sideloading - if it says "searching for Wi-Fi devices" it means it didn't detect you being connected to your computer

So make sure it's plugged into your computer and ScarletCloud is open

**Comment by fqhy** [comment]
Why would you close the ticket? The fact that some apps aren’t sideloading is still in place and fact that sideloaded app is not showing up in Scarlet is still in place.

**Comment by DebianArch64** [comment]
> Why would you close the ticket? The fact that some apps aren’t sideloading is still in place and fact that sideloaded app is not showing up in Scarlet is still in place.

Because the "Searching for Wi-Fi devices." Isn't an error message it's a status. Plug and replug your device as stated earlier as your phone isn't detecting a computer.

It's not stuck on 99% sideloading either - the percentage menu closes when the computer closes the connection or when the app is finished sideloading to the phone.

Also do note that apple has a restriction of three apple account apps at a time
