### ISSUE TITLE
lockdown start session:receive packet: invalidhost id

### ISSUE THREAD

**Issue by lengxiao86** [DebianArch64/DebProvision#81]
try to install again, it shows:   "lockdown start session:receive packet: invalidhostID“
![Screenshot 2022-12-23 194723](https://user-images.githubusercontent.com/52514697/209331630-1f03f218-3956-48ca-99f5-83173e6f161b.png)

**Comment by DebianArch64** [comment]
> try to install again, it shows: "lockdown start session:receive packet: invalidhostID“ ![Screenshot 2022-12-23 194723](https://user-images.githubusercontent.com/52514697/209331630-1f03f218-3956-48ca-99f5-83173e6f161b.png)

Try turning on and off your computer - all usb based communications are handled with apples official muxer
