### ISSUE TITLE
Install IPA fail

### ISSUE THREAD

**Issue by lengxiao86** [DebianArch64/DebProvision#82]
Try to install IPA. in SCARLET shows ok. But go back to desktop, it shows the app as a cloud.
![photo_2022-12-23_23-07-09](https://user-images.githubusercontent.com/52514697/209357612-3cf4f4de-dd5c-4cca-96a8-be64357d27bd.jpg)
![photo_2022-12-23_23-07-13](https://user-images.githubusercontent.com/52514697/209357645-614345c2-780b-4763-9f30-f0a0e7e0ef43.jpg)

**Comment by Zany-Zachary1** [comment]
Not entirely sure, but worth a shot.  This may be because the version in your IPA's `info.plist` file is mismatched with your current iOS version.  To fix this, try to extract the IPA and change the `info.plist` file's version number to yours.

**Comment by lengxiao86** [comment]
it is quite strange. If I use resources.usescarlet.com to install the scarlet(install directly), then the scarlet can install IPA sucess.

**Comment by DebianArch64** [comment]
New ScarletCloud update is being worked on that adds new errors when it can't get the device UDID - along with many login based improvements

I'll make sure to make a post here when the update releases - you can also see my @GetScarlet twitter page.

For some reason I'm unable to replicate the message you got on my devices, but will look urgently into it

**Comment by lengxiao86** [comment]
more details, I‘m using wireless mode:Wireguard -> Import the "emp.conf" into Wireguard from the App Store | @jkcoxson allowed this mode to be possible.

**Comment by DebianArch64** [comment]
> more details, I‘m using wireless mode:Wireguard -> Import the "emp.conf" into Wireguard from the App Store | @jkcoxson allowed this mode to be possible.

Does Scarlet give you a message inside the app of how it failed ? Make sure to stay inside the app and screenshot the error message it says it'll help me fix the issue for you

**Comment by lengxiao86** [comment]
> 

I fixed it. The issue mostly like my apple ID, i changed to another Apple  ID, the IPA can be installed correctly. 
But, I found a new issue. Some IPA shows error like following
![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)

**Comment by DebianArch64** [comment]
> > 
> 
> I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)

Send me the IPA that you are experiencing issues with

**Comment by lengxiao86** [comment]
> > > 
> > 
> > 
> > I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> 
> Send me the IPA that you are experiencing issues with

here it is
https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa

**Comment by DebianArch64** [comment]
> > > > 
> > > 
> > > 
> > > I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> > 
> > 
> > Send me the IPA that you are experiencing issues with
> 
> here it is https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa

![Screenshot_20221224-212341](https://user-images.githubusercontent.com/63203414/209456120-20d33dc9-90d1-4a47-a813-5251bb00193f.png)

Looks like it's caused because the app has no name. When registering the app on your account it uses the name Scarlet gets from the IPA

Changes can be made in the future to support apps with no names

**Comment by lengxiao86** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> > > 
> > > 
> > > Send me the IPA that you are experiencing issues with
> > 
> > 
> > here it is https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa
> 
> ![Screenshot_20221224-212341](https://user-images.githubusercontent.com/63203414/209456120-20d33dc9-90d1-4a47-a813-5251bb00193f.png)
> 
> Looks like it's caused because the app has no name. When registering the app on your account it uses the name Scarlet gets from the IPA
> 
> Changes can be made in the future to support apps with no names

it is strange. I used the website scarlet, install directly. That scarlet can install this IPA properly.

**Comment by DebianArch64** [comment]
I'll also be closing this issue as complete because windows now supports la

> > > > > > 
> > > > > 
> > > > > 
> > > > > I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> > > > 
> > > > 
> > > > Send me the IPA that you are experiencing issues with
> > > 
> > > 
> > > here it is https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa
> > 
> > 
> > ![Screenshot_20221224-212341](https://user-images.githubusercontent.com/63203414/209456120-20d33dc9-90d1-4a47-a813-5251bb00193f.png)
> > Looks like it's caused because the app has no name. When registering the app on your account it uses the name Scarlet gets from the IPA
> > Changes can be made in the future to support apps with no names
> 
> it is strange. I used the website scarlet, install directly. That scarlet can install this IPA properly.

Scarlet direct doesn't have to register the app to your account lol

**Comment by lengxiao86** [comment]
> I'll also be closing this issue as complete because windows now supports la
> 
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> > > > > 
> > > > > 
> > > > > Send me the IPA that you are experiencing issues with
> > > > 
> > > > 
> > > > here it is https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa
> > > 
> > > 
> > > ![Screenshot_20221224-212341](https://user-images.githubusercontent.com/63203414/209456120-20d33dc9-90d1-4a47-a813-5251bb00193f.png)
> > > Looks like it's caused because the app has no name. When registering the app on your account it uses the name Scarlet gets from the IPA
> > > Changes can be made in the future to support apps with no names
> > 
> > 
> > it is strange. I used the website scarlet, install directly. That scarlet can install this IPA properly.
> 
> Scarlet direct doesn't have to register the app to your account lol
> 
> Signing with an apple account means creating a Mobileprovision by asking apple to make one with a given name and bundleId - if the name is null the error you received happens
> 
> Direct version is a wildcard mobileprovision they don't need any registrations they just work

got it. Looking forward a new verison to support non-name IPA. ：）

**Comment by DebianArch64** [comment]
> > I'll also be closing this issue as complete because windows now supports la
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > I fixed it. The issue mostly like my apple ID, i changed to another Apple ID, the IPA can be installed correctly. But, I found a new issue. Some IPA shows error like following. What I should do? ![photo_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> > > > > > 
> > > > > > 
> > > > > > Send me the IPA that you are experiencing issues with
> > > > > 
> > > > > 
> > > > > here it is https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa
> > > > 
> > > > 
> > > > ![Screenshot_20221224-212341](https://user-images.githubusercontent.com/63203414/209456120-20d33dc9-90d1-4a47-a813-5251bb00193f.png)
> > > > Looks like it's caused because the app has no name. When registering the app on your account it uses the name Scarlet gets from the IPA
> > > > Changes can be made in the future to support apps with no names
> > > 
> > > 
> > > it is strange. I used the website scarlet, install directly. That scarlet can install this IPA properly.
> > 
> > 
> > Scarlet direct doesn't have to register the app to your account lol
> > Signing with an apple account means creating a Mobileprovision by asking apple to make one with a given name and bundleId - if the name is null the error you received happens
> > Direct version is a wildcard mobileprovision they don't need any registrations they just work
> 
> got it. Looking forward a new verison to support non-name IPA. ：）

You're helping me alot with these bug reports - I've posted quite a bit of bug fixes for both ScarletCloud and Scarlet now

I'll tell you when the computer method supports no names

**Comment by Maicom12** [comment]
> 
[Uploading ScarletAlpha.ipa.zip…]()

**Comment by juanpredu** [comment]
> Tente instalar o IPA. em SCARLET mostra ok. Mas volte para a área de trabalho, ele mostra o aplicativo como uma nuvem. ![foto_2022-12-23_23-07-09](https://user-images.githubusercontent.com/52514697/209357612-3cf4f4de-dd5c-4cca-96a8-be64357d27bd.jpg) ![foto_2022-12-23_23-07-13](https://user-images.githubusercontent.com/52514697/209357645-614345c2-780b-4763-9f30-f0a0e7e0ef43.jpg)

this problem occurs because ios only allows the installation of 3 apps with scarletcloud

**Comment by juanpredu** [comment]
> > > Também fecharei este problema como completo porque o Windows agora suporta la
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Eu consertei isso. O problema é principalmente como meu ID da Apple, mudei para outro ID da Apple, o IPA pode ser instalado corretamente. Mas, eu encontrei um novo problema. Alguns IPA mostram erros como o seguinte. O que eu deveria fazer?![foto_2022-12-24_16-02-43](https://user-images.githubusercontent.com/52514697/209426948-0155decc-7fa8-47e6-9e3e-ee8f99d387d4.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > Envie-me o IPA com o qual você está tendo problemas
> > > > > > 
> > > > > > 
> > > > > > aqui está https://github.com/yuuwill/1024app-ios/releases/download/v2.3.5/1024app_ios_2.3.5.ipa
> > > > > 
> > > > > 
> > > > > ![Captura de tela_20221224-212341](https://user-images.githubusercontent.com/63203414/209456120-20d33dc9-90d1-4a47-a813-5251bb00193f.png)
> > > > > Parece que é causado porque o aplicativo não tem nome. Ao registrar o aplicativo em sua conta, ele usa o nome que Scarlet recebe do IPA 
> > > > > Alterações podem ser feitas no futuro para oferecer suporte a aplicativos sem nomes
> > > > 
> > > > 
> > > > isto é estranho. Eu usei o site scarlet, instale diretamente. Esse escarlate pode instalar este IPA corretamente.
> > > 
> > > 
> > > O Scarlet direct não precisa registrar o aplicativo em sua conta lol 
> > > Assinar com uma conta da apple significa criar um Mobileprovision solicitando à apple que crie um com um determinado nome e bundleId - se o nome for nulo, o erro que você recebeu acontecerá 
> > > A versão direta é um wildcard mobileprovision eles não precisam de nenhum registro, eles apenas funcionam
> > 
> > 
> > Entendi. Ansioso por uma nova versão para oferecer suporte a IPA sem nome. ：）
> 
> Você está me ajudando muito com esses relatórios de bugs - eu postei algumas correções de bugs para ScarletCloud e Scarlet agora
> 
> Eu vou te dizer quando o método de computador não suporta nomes

I also had problems with this error, the solution is simple, just connect the cell phone to the PC whenever you install an app, and open the scarletcloud installation application (on the PC), after that you can install the applications on the cell phone.

**Comment by DebianArch64** [comment]
Scarlet supports any bundleId and name in new updates - automatically converts them into ASCII form that apple API allows
