### ISSUE TITLE
Apps after sideloading don’t show up and some apps don’t sideload at all

### ISSUE THREAD

**Issue by fqhy** [DebianArch64/DebProvision#83]
ScarletServer is latest version and A11 on 15.6. After installing some apps like uYou+, ScarletServer shows that app was successfully sideloaded, but in reality app is not showing up in both app and Scarlet don’t show that app is installed. After sideloading another app, it was successfully sideloaded as stated in ScarletServer, and it did show up on home screen, but in Scarlet it does not show.

**Comment by DebianArch64** [comment]
> ScarletServer is latest version and A11 on 15.6. After installing some apps like uYou+, ScarletServer shows that app was successfully sideloaded, but in reality app is not showing up in both app and Scarlet don’t show that app is installed. After sideloading another app, it was successfully sideloaded as stated in ScarletServer, and it did show up on home screen, but in Scarlet it does not show.

Do you already have three apple accounts installed (this includes the Scarlet app itself)

**Comment by lts20050703** [comment]
I get the `afc file receive 'Read': receive packet (afc): EOF` error trying to sideload uYouPlus IPA, even though there are only 2 apps sideloaded (scarlet and enmity)
![image](https://user-images.githubusercontent.com/87189679/209422193-861b25d4-1d00-4d52-8f02-b0452b5f57a2.png)

**Comment by lts20050703** [comment]
Neverminf after a few tries it successfully sideloaded uYouPlus

**Comment by DebianArch64** [comment]
> Nevermind after a few tries it successfully sideloaded uYouPlus

AFC is a service by apple for file transfer - if it failed reading packets it's likely another program was reading the packets ScarletCloud was supposed to receive
