### ISSUE TITLE
Can't install without pc (wireguard mode)

### ISSUE THREAD

**Issue by agungrbudiman** [DebianArch64/DebProvision#85]
![IMG_0164](https://user-images.githubusercontent.com/16059175/209489832-2159ed82-3c15-4ddc-9cf1-07083ebec0f5.jpg)
`failed to get anisette (Get "": unsupported protocol scheme "")` . It seems scarlet can't get list of anisette servers which will be used for no pc method (emp.conf with wireguard).

**Comment by DebianArch64** [comment]
> ![IMG_0164](https://user-images.githubusercontent.com/16059175/209489832-2159ed82-3c15-4ddc-9cf1-07083ebec0f5.jpg) `failed to get anisette (Get "": unsupported protocol scheme "")` . It seems scarlet can't get list of anisette servers which will be used for no pc method (emp.conf with wireguard).

Not exactly - my GSA library got a modification which helps enforce no anisette servers for windows and Mac

The "" empty string is used for me to signify to use the default Scarlet anisette servers. I'll definitely look more into how this new update semi-broke it - for now choose an anisette server in the anisette selector menu (3D touch the sideload button)

**Comment by agungrbudiman** [comment]
Thanks for the tips, manually select anisette server resolve the issue.
