### ISSUE TITLE
estalei o scarlet  errei o email

### ISSUE THREAD

**Issue by ocarliinhos** [DebianArch64/DebProvision#87]
estalei o scarlet  pelo pc e tudo ok na hora de abri o app pediu email e senha mas digitei errado e dei ok, nao to conseguindo reinstalar pra pediu a senha, retirei e estalei de novo mas nao pede mais a senha, alguem com algum modo de pedir novamente email e senha ?

**Comment by ocarliinhos** [comment]
qualquer coisa me chama 6198492767 ou no email carlospradofc@gmail.com

**Comment by DebianArch64** [comment]
https://twitter.com/GetScarlet/status/1607375257270194177?t=dG0lkXGX0geY0Kf37P9FEQ&s=19
^^ this video shows how you can logout

I'll also make sure to automatically logout of the account in the next update.
