### ISSUE TITLE
an option to add your own mobileprovision and p12 file in scarlet

### ISSUE THREAD

**Issue by DetachHead** [DebianArch64/DebProvision#9]

**Comment by DebianArch64** [comment]
I'll see about adding this today - Scarlet app itself already supports importing your own certificate, but ScarletCloud disables this functionality and I forgot to re-enable it

I'll close this issue when it's added

**Comment by DetachHead** [comment]
@DebianArch64 any update on this?

**Comment by ImArxzy** [comment]
How do you download the scarlet cloud, I'm having a difficult time.

**Comment by K7767** [comment]
🔥🔥🔥🔥
