### ISSUE TITLE
Failed installing scarlet: TLS handshake timeout

### ISSUE THREAD

**Issue by lts20050703** [DebianArch64/DebProvision#91]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/87189679/209826056-f1cd9325-d714-4e8e-9db9-1e188cd53eaa.png">

**Comment by lts20050703** [comment]
Try again, now getting timeout awaiting response headers

<img width="855" alt="image" src="https://user-images.githubusercontent.com/87189679/209826696-4cb2f2bc-83d6-4bfb-837c-d2a8874c478b.png">

**Comment by DebianArch64** [comment]
> Try again, now getting timeout awaiting response headers
> 
> <img alt="image" width="855" src="https://user-images.githubusercontent.com/87189679/209826696-4cb2f2bc-83d6-4bfb-837c-d2a8874c478b.png">

Timeout based errors is when your computer doesn't recieve a response fast enough. I believe the TLS wait time is 15 seconds which is more than enough, but I can boost it to a minute in the next update

Make sure you have a good internet connection and it'll work fine - could also be that apples servers are slow
