### ISSUE TITLE
No Longer Supports Standalone Sideloading

### ISSUE THREAD

**Issue by gharshit606** [DebianArch64/DebProvision#92]
Hi there, I am a big fan of your work, the project you are doing to make sideloading easier for IOS. Previously, the app works really good which doesn’t requires any computer at all to sideload any IPA and this was the main highlight which was working as a USP for this app, even in its promotion too. But now it requires to be connected with a computer to work as it unable to get local anisette without computer and locks the apple id which again makes it same just like Altstore and Sideloadly.
Just asking out of curiosity as i am also learning coding and programming languages , Can you tell me whats the reason behind that it was able to acquire local anisette by its own previously, but now from few days it requires computer for the same…

Another thing i wanna ask you is about open sourcing this project, i saw a query of someone asking for the same, then you said that people used to copy the project without giving credits. Well, whats my thought on that is if someone even copy it like making a youtube video or something, then the audience which are watching such kinda Nerdy content also used to research for the actual owner of the project so that they can help the project by reporting bugs, etc. just like we are doing here.. So according to me there is no concern of getting credit as the creator always get it automatically at the end of the day… So whats your your opinion in open sourcing it in future?
![51481B0D-0C9C-412B-8BDD-FD114E679CC1](https://user-images.githubusercontent.com/119405395/210173239-bb9514cb-12bb-4d15-8327-1ffd7458c28c.png)

**Comment by DebianArch64** [comment]
> Hi there, I am a big fan of your work, the project you are doing to make sideloading easier for IOS. Previously, the app works really good which doesn’t requires any computer at all to sideload any IPA and this was the main highlight which was working as a USP for this app, even in its promotion too. But now it requires to be connected with a computer to work as it unable to get local anisette without computer and locks the apple id which again makes it same just like Altstore and Sideloadly. Just asking out of curiosity as i am also learning coding and programming languages , Can you tell me whats the reason behind that it was able to acquire local anisette by its own previously, but now from few days it requires computer for the same…
> 
> Another thing i wanna ask you is about open sourcing this project, i saw a query of someone asking for the same, then you said that people used to copy the project without giving credits. Well, whats my thought on that is if someone even copy it like making a youtube video or something, then the audience which are watching such kinda Nerdy content also used to research for the actual owner of the project so that they can help the project by reporting bugs, etc. just like we are doing here.. So according to me there is no concern of getting credit as the creator always get it automatically at the end of the day… So whats your your opinion in open sourcing it in future? ![51481B0D-0C9C-412B-8BDD-FD114E679CC1](https://user-images.githubusercontent.com/119405395/210173239-bb9514cb-12bb-4d15-8327-1ffd7458c28c.png)

The direct method didn't use login or anisette. Anisette is something specifically for xcodes API

Direct method uses Enterprise certificates it's not discontinued - if you have your own development certificate you can import it into Scarlet
