### ISSUE TITLE
Can’t log in setup native anisette

### ISSUE THREAD

**Issue by jonahnm** [DebianArch64/DebProvision#93]
This error occurs when attempting to do anything except enable JIT

**Comment by jonahnm** [comment]
Attempting to change anisette server causes scarlet to crash

**Comment by DebianArch64** [comment]
> Attempting to change anisette server causes scarlet to crash

This is a known issue for iPad - I'll need to check it on the simulator since I don't own an iPad

I will also get to fixing the login library to support the default anisette server again

**Comment by DebianArch64** [comment]
This issue is now fixed btw - minus the iPad stuff, but that shouldn't be needed anymore
