### ISSUE TITLE
Not entirely sure, but worth a shot.  This may be because the version in your IPA's `info.plist` file is mismatched with your current iOS version.  To fix this, try to extract the IPA and change the `info.plist` file's version number to yours.

### ISSUE THREAD

**Issue by Maicom12** [DebianArch64/DebProvision#97]
Not entirely sure, but worth a shot.  This may be because the version in your IPA's `info.plist` file is mismatched with your current iOS version.  To fix this, try to extract the IPA and change the `info.plist` file's version number to yours.

_Originally posted by @SpektacleFR in https://github.com/DebianArch64/DebProvision/issues/82#issuecomment-1364048968_

**Comment by DebianArch64** [comment]
> ```
>           Not entirely sure, but worth a shot.  This may be because the version in your IPA's `info.plist` file is mismatched with your current iOS version.  To fix this, try to extract the IPA and change the `info.plist` file's version number to yours.
> ```
> 
> 
>      
>   
> 
> _Originally posted by @SpektacleFR in [#82 (comment)](https://github.com/DebianArch64/DebProvision/issues/82#issuecomment-1364048968)_

Scarlet already automatically removes UI device dependencies and version dependencies from the Info.plist. If you have any issues with an IPA make sure to give me a DM with the error you have on Discord or Twitter

Twitter: @DebianArch
Discord: DebianArch#1935
